#+TITLE: Orals Lists
#+OPTIONS: num:nil toc:nil

* Utopian Studies

#+BEGIN_VERSE
Baccolini, Raffaella. /Dark Horizons./ (2003)
Bacon, Francis. /New Atlantis./ (1624-1626)
Bellamy, Edward. /Looking Backward./ (1888)
Bloch, Ernst. /The Principle of Hope./ (1954)
Bould, Mark and China Miéville. /Red Planets: Marxism and Science Fiction./ (2009)
Davis, J.C. /Utopia and the Ideal Society: A Study of English Utopian Writing 1516-1700./ (1983)
Davis, Laurence. /Anarchism and Utopianism. ./ (2010)
Edelman, Lee. /No Future: Queer Theory and the Death Drive/ (2004)
Hardt, Michael, and Antonio Negri. /Empire./ (200)
Harvey, David. /Spaces of Hope./ (2000)
Hertzler, Joyce. /History of Utopian Thought./ (1965)
Jameson, Frederic. /Archeologies of the Future./ (2005)
Kumar, Krishan. /Utopia and Anti-Utopia in Modern Times../ (1991)
Lavander, Isiah./Race in American Science Fiction./ (2011)
Levine, Caroline. /Forms: Whole, Rhythm, Hierarchy, Network/. (2015)
London, Jack. /The Iron Heel./ (1908)
McBride, Keally. /Collective Dreams: Political Imagination and Community. ./ (2005)
More, Thomas. /Utopia./ (1516)
Morton, Timothy/Ecology Without Nature: Rethinking Environmental Aesthetics ./ (2009)
Moylan, Tom. /Scraps of the Untainted Sky./ (2000)
Muñoz, José Esteban. /Cruising Utopia: The Then and There of Queer Futurity/. (2009)
Nassa, Anthony. ./The Spirit of Utopia/ (1923)
Piercy, Marge. /Woman at the Edge of Time./ (1976)
Pordzik, Ralph. /The Quest for the Postcolonial Utopia./ (2001)
Rawson, Claude. /God, Gulliver, and Genocide./ (2001)
Roberts, Adam. /Science Fiction: New Critical Idiom/ (2000)
Sargent, Lyman Tower. /Three Faces of Utopianism Revisited/ (1994)
Schaer, Roland, Gregory Claeys, and Lyman Tower Sargent. /Utopia: The Search for the Ideal Society in the Western World./  (2001)
Stross, Charles. /Accelerando./ (2005)
Suvin, Darko. /Metamorphoses of Science Fiction./ (1979)
Swift, Jonathan. /Gulliver's Travels./ (1726)
Tom Moylan. /Demand the Impossible: Science Fiction and the Utopian Imagination./ (2014)
William, Morris. /News from Nowhere./ (1890)
Williams, Raymond. /Tenses of Imagination./ (2010)
#+END_VERSE
* Victorian Science

#+BEGIN_VERSE
Alioto, Anthony. /A History of Western Science/. (1992)
Altick, Richard. /Deadly encounters: Two Victorian Sensations./ (1986)
Beer, Gillian. /Darwin's Plots/. (2009)
Blaise, Clark. /Time Lord: Sir Sandford Fleming and the Creation of Standard Time/. (2002)
Bowler, Peter J. /Evolution: The History of an Idea./ (1989o 
Brantlinger, Patrick. /Rule of darkness: British literature and imperialism,1830–1914/. (1988)
Butler, Samuel. /Erewhon./ (1872)
Chambers, Robert. /Vestiges of the Natural History of Creation/. (1844)
Claussen, Christopher. "Sherlock Holmes, order and the late-Victorian mind." (1984)
Collins, Wilkie. /The Moonstone/. (1868)
Darwin, Charles. /The Descent of Man'. (1871)
Darwin, Charles. /The Origin of Species/. (1859)
DeWitt, Anne. /Moral Authority, Men of Science, and the Victorian Novel/. (2013)
Doyle, Arthur Conan. /The Adventures of Sherlock Holmes/. (1887-1917)
Doyle, Arthur Conan. /The Hound of the Baskervilles/. (1901-1902)
Doyle, Arthur Conan. /The Lost World/. (1912)
Gould, Stephen Jay and R. C. Lewontin.. "The Spandrels of San Marco and the Panglossian Paradigm: A Critique of the Adaptationist Programme." (1979)
Kingsley, Charles. /The Water-Babies/. (1862)
Kohn, David. /The Darwinian Heritage/. (1985)
Kuhn, thomas s. /The Structure of Scientific Revolutions/. (1962)
Levine, George. /Darwin and the Novelists: Patterns of Science in Victorian Fiction./. (1992)
Lightman, Bernard. /Victorian Science in Context/. (1997)
Marks, John M. /Science and the Making of the Modern World./ (1984)
Marsh, Richard. /The Beetle./ (1897)
Mill, John Stuart. /A System of Logic/. (1843)
Moskowitz, Sam. /Science Fiction by Gaslight: A History and Antho logy of Science Fiction in the Popular Magazines, 1891-1911/. (1974)
Murphy, Patricia, /In Science’S Shadow Literary Constructions of Late Victorian Women/. (2006)
Renk, Kathleen J. /Magic, Science, and Empire in Postcolonial Literature : The Alchemical Literary Imagination./ (2012)
Schivelbusch, Wolfgang. /The Railway Journey: The Industrialization of Time and Space in the 19th Century/. (1979)
Secord, J.A. /Knowledge in Transit/. (2004)
Shapin, Steven and Simon Schaffer. /Leviathan and the Air Pump./ (1985)
Snow, C. P. /The Two Cultures/. (1959)
Stevenson, Robert Louis. /The Strange Case of Dr. Jekyll and Mr. Hyde./ (1886)
Stoker, Bram. /Dracula/. (1886)
#+END_VERSE
* Futures of the Book

#+BEGIN_VERSE
Austin,  J. L. /How to Do Things with Words/. (presented 1955, published 1962)
Bayard, Pierre. /How to Talk About Books You Haven't Read/. (2010)
Benjamin, Walter. “The Work of Art in the Age of Mechanical Reproduction." (1936)
Benkler, Y. /The Wealth of Networks: How Social Production Transforms Markets and Freedom./ (2006)
Bolter, David J. /Writing Space: Computers, Hypertext, and the History of Writing./ (2001)
Chartier, Roger. /Forms and Meanings: Texts, Performances, and Audiences from Codex to Computer./ (1995)
Darnton, Robert. /The Case for Books: Past, Present, and Future./ (2009)
Dexter, Scott and Samir Chopra.  /Decoding Liberation Software: The Promise of Free and Open Source Software./ (2007)
Doctorow, C. /Content: Selected essays on technology, creativity, copyright, and the future of the future./ (2008)
Drucker, Johanna. "Data as Capta," DHQ (2011)
Emerson, Lori. /Reading Writing Interfaces: From the Digital to the Bookbound./ (2014)
Fitzpatrick, Kathleen. /Planned Obselescence./ (2011)
Flusser, Vilem. /Does Writing Have a Future?/ (2011)
Franco Moretti. /Graphs, Maps, Trees: Abstract Models for a Literary History./ (2005)
Genette, G. /Paratexts: Thresholds of interpretation./. (1997)
Gitelman, Lisa. /Paper Knowledge: Toward a Media History of Documents./ (2014)
Gold, Matthew K. /(Ed). Debates in the Digital Humanities./ (2012)
Greetham, David. /Theories of the Text./ (1994)
Hayles, Katherine N. and Jessica Pressman, Editors /Comparative Textual Media./ (2013)
James Gleick. /The Information: A History, A Theory, A Flood./ (2011)
Johns, Adrian. /The Nature of the Book: Print and Knowledge in the Making./ (1998)
Jones, Steve. /Emergence of Digital Humanities./ (2013)
Kelty, Christopher./Two Bits: The Cultural Significance of Free Software./(2008)
Kirschenbaum, Matthew.. /Mechanisms: New Media and the Forensic Imagination./ (2008)
Kirschenbaum, Matthew.. /Track Changes: A Literary History of Word Processing/. (2016)
Kitler, Friedrich., /Literature, Media, Information Systems/ (1997)
Lessig, Lawrence. /Remix: Making Commerce Thrive in the Hybrid Economy./ (2008)
McGann, Jerome. /Radient Textuality./ (2004)
McKenzie, D. F. /Bibliography and the Sociology of Texts./ (1999)
McLuhan, Marshall.. /The Gutenberg Galaxy./ (1962)
Nelson, Ted. /Computer Lib/Dream Machines./ (1974)
Piper, Andrew. /Book Was There: Reading in Electronic./ (2013 reprint)
Siemens, R., Timney, M., Leitch, C., Koolen, C., & Garnett, A. (2012). /Toward modeling the social edition: An approach to understanding the electronic scholarly edition in the context of new and emerging social media." (2014)
Stallman, Richard. /Free Software Free Society./ (2009)
Stephen Ramsay. /Reading Machines: Toward an Algorithmic Criticism./ (2011)
Underwood, Ted. The Literary Uses of High-Dimensional Space." (2015)
Walter Ong, /Orality and Literacy: The Technologizing of the Word./ (1982)
Wolfgang Ernst. /Digital Memory and the Archive./ (2012)
#+END_VERSE
