#+TITLE: Orals Lists
#+OPTIONS: num:nil toc:nil

* Utopian Studies
Baccolini, Raffaella. /Dark Horizons./ (2003)
Bellamy, Edward. /Looking Backward./ (1888)
Bloch, Ernst. /The Principle of Hope./ (1954)
Bould, Mark and China Miéville. /Red Planets: Marxism and Science Fiction./ (2009)
Davis, J.C. /Utopia and the Ideal Society: A Study of English Utopian Writing 1516-1700./ (1983)
Davis, Laurence. /Anarchism and Utopianism. ./ (2010)
Hardt, Michael, and Antonio Negri. /Empire./ (200)
Harvey, David. /Spaces of Hope./ (2000)
Hertzler, Joyce. /History of Utopian Thought./ (1965)
Jameson, Frederic. /Archeologies of the Future./ (2005)
Kumar, Krishan. /Utopia and Anti-Utopia in Modern Times../ (1991)
Lavander, Isiah./Race in American Science Fiction./ (2011)
London, Jack. /The Iron Heel./ (1908)
McBride, Keally. /Collective Dreams: Political Imagination and Community. ./ (2005)
Morton, Timothy/Ecology Without Nature: Rethinking Environmental Aesthetics ./ (2009)
Moylan, Tom. /Scraps of the Untainted Sky./ (2000)
Nassa, Anthony. ./The Spirit of Utopia/ (1923)
Pordzik, Ralph. /The Quest for the Postcolonial Utopia./ (2001)
Rawson, Claude. /God, Gulliver, and Genocide./ (2001)
Roberts, Adam. /New Critical Idiom./ (2000)
Sarovic, Aleksandar. /Humanism./ (2009)
Schaer, Roland, Gregory Claeys, and Lyman Tower Sargent. /Utopia: The Search for the Ideal Society in the Western World./  (2001)
Tom Moylan. /Demand the Impossible: Science Fiction and the Utopian Imagination./ (2014)
Williams, Raymond. /Tenses of Imagination./ (2010)
William, Morris. /News from Nowhere./ (1890)
* Futures of the Book
Adrian Johns. /The Nature of the Book: Print and Knowledge in the Making./ (1998)
Benjamin, Walter. “The Work of Art in the Age of Mechanical Reproduction."
Benkler, Y. /The Wealth of Networks: How Social Production Transforms Markets and Freedom./ (2006)
Bolter, David J. /Writing Space: Computers, Hypertext, and the History of Writing./ (2001)
Chartier, Roger. /Forms and Meanings: Texts, Performances, and Audiences from Codex to Computer./ (1995)
Darnton, Robert. /The Case for Books: Past, Present, and Future./ (2009)
Dexter, Scott and Samir Chopra.  /Decoding Liberation Software: The Promise of Free and Open Source Software./ (2007)
Doctorow, C. /Content: Selected essays on technology, creativity, copyright, and the future of the future./ (2008)
Drucker, Johanna. "Data as Capta," DHQ (2011)
Emerson, Lori. /Reading Writing Interfaces: From the Digital to the Bookbound./ (2014)
Fitzpatrick, Kathleen. /Planned Obselescence./ (2011)
Flusser, Vilem. /Does Writing Have a Future?/ (2011)
Franco Moretti. /Graphs, Maps, Trees: Abstract Models for a Literary History./ (2005)
Genette, G. /Paratexts: Thresholds of interpretation./. (1997)
Gold, Matthew K. /(Ed). Debates in the Digital Humanities./ (2012)
Greetham, David. /Theories of the Text./ (1994)
Hayles, Katherine N. and Jessica Pressman, Editors /Comparative Textual Media./ (2013)
James Gleick. /The Information: A History, A Theory, A Flood./ (2011)
Jones, Steve. /Emergence of Digital Humanities./ (2013)
Kelty, Christopher./Two Bits: The Cultural Significance of Free Software./(2008)
Kitler, Friedrich., /Literature, Media, Information Systems/ (1997)
Lessig, Lawrence. /Remix: Making Commerce Thrive in the Hybrid Economy./ (2008)
Lisa Gitelman, /Paper Knowledge: Toward a Media History of Documents./ (2014)
Marshall McLuhan. /The Gutenberg Galaxy./ (1962)
Matthew Kirschenbaum. /Mechanisms: New Media and the Forensic Imagination./ (2008)
McGann, Jerome. /Radient Textuality./ (2004)
McKenzie, D. F. /Bibliography and the Sociology of Texts./ (1999)
Michel Foucault, /The Archaeology of Knowledge./ (1969) 
Piper, Andrew. /Book Was There: Reading in Electronic./ (2013 reprint)
Siemens, R., Timney, M., Leitch, C., Koolen, C., & Garnett, A. (2012). /Toward modeling the social edition: An approach to understanding the electronic scholarly edition in the context of new and emerging social media.". Literary and Linguistic Computing, 27(4)
Stallman, Richard. /Free Software Free Society./ (2009)
Stephen Ramsay. /Reading Machines: Toward an Algorithmic Criticism./ (2011)
Underwood, Ted. The Literary Uses of High-Dimensional Space." (2015)** Walter Ong, /Orality and Literacy: The Technologizing of the Word./ (1982)
Wolfgang Ernst. (Ed.) /Digital Memory and the Archive./ (2012)
* Victorian Science
Alioto, Anthony. /A History of Western Science/. (1992)
Altick, Richard. /Deadly encounters: Two Victorian Sensations./ (1986)
Beer, Gillian. /Darwin's Plots/. (2009)
Blaise, Clark. /Time Lord: Sir Sandford Fleming and the Creation of Standard Time/. (2002)
Bowler, Peter J. /Evolution: The History of an Idea./ (1989)
Brantlinger, Patrick. /Rule of darkness: British literature and imperialism,1830–1914/. (1988)
Butler, Samuel. /Erewhon./ (1872)
Claussen, Christopher. "Sherlock Holmes, order and the late-Victorian mind." in /Georgia Review/ (1984)
Collins, Wilkie. /The Moonstone/. (1868)
Collins, Wilkie. /The Woman in White/. (1859)
Darwin, Charles. /The Origin of Species/. (1859)
DeWitt, Anne. /Moral Authority, Men of Science, and the Victorian Novel/. (2013)
Dickens, Charles. /Bleak House/. (1853)
Doyle, Arthur Conan. /Horror of the Heights/. (1913).
Doyle, Arthur Conan. /The Adventures of Sherlock Holmes/. (--)
Doyle, Arthur Conan. /The Lost World/. (1912)
Harben, William. /The Land of the Changing Sun/. (1894)
Houghton, Walter. /The Victorian Frame of Mind/. (1963)
Kohn, David. /The Darwinian Heritage/. (1985)
Kuhn, thomas s. /The Structure of Scientific Revolutions/. (1962)
Lang, Andrew. /The Book of Dreams and Ghosts./. (1897)
Levine, George. /Darwin and the Novelists: Patterns of Science in Victorian Fiction./. 
Lightman, Bernard. /Victorian Science in Context/. (1997)
Marks, John M. /Science and the Making of the Modern World./ (1984)** mill, john stuart. /Autobiography/. (1873)
Marsh, Richard. /The Beetle./
Merritt, A. /The Moon Pool/. (1918)
Moskowitz, Sam. /Science Fiction by Gaslight: A History and Antho logy of Science Fiction in the Popular Magazines, 1891-1911/. (1974)
Murphy, Patricia, /In Science’S Shadow Literary Constructions of Late Victorian Women/. (2006)
Renk, Kathleen J. /Magic, Science, and Empire in Postcolonial Literature : The Alchemical Literary Imagination./ (2012)
Stevenson, Robert Louis. "The Strange Case of Dr. Jekyll and Mr. Hyde."
Stoker, Bram. /Dracula./
Stoker, Bram. /Dracula/. (1886)
Strick, James Edgar. /Sparks of Life: Darwinism and the Victorian Debates over Spontaneous Generation/. (2000)
Taylor, Jenny Bourne. /In the Secret Theatre of Home: Wilkie Collins, Sensation Narrative, and Nineteenth-Century Psychology/. (1988)
Thrower, Norman J. W. /Maps and Civilization/. (1996)
William Coleman, /Biology in the Nineteenth Century/. (1977)
