* Rationale

Every ideology has a vision for the future. Whether anticipation of the collapse of a bourgeois ruling class, the rise of "disruptive" technologies that "change the world," or the advancement (or reactionary response to) progressive social causes, each social, political, or cultural movement looks forward to a future that necessitates action (or reaction) in the present. These visions of the future can be exhaustively detailed—/Novum Organum/, /Das Kapitel/, /Atlas Shrugged/\—or open-ended, suggestive, and implicit, as with the neoliberalism of Milton Friedman, the optimism of the Occupy movement, or the utopian promises of "block chain" technology. By shaping hopes and expectations for the future, social movements—cultural and technological, progressive and reactionary—advance their aims and define the ground on which intellectural and artistic expression can occur. By mastering these rhetorics of the future, leaders, artists, and philosophers can extend or constrain the forms of the present, redefining normative values and reshaping society in their own image. 

For my orals examination, I propose to explore these rhetorics of the future from three directions: Utopian Studies, Victorian Science, and the Future of the Book. As a field concerned with futurity, imagination, and intentional communities and spaces, Utopian Studies will provide a methodological and theoretical grounding for a sustained look at rhetorics based on shared visions of the future. My other lists, Victorian Science and The Future of the Book, will provide fascinating subjects for the examination of future rhetorics. Victorian Science and The Future of the Book represent ideological spaces that are heterodox and widely influential.

My  Utopian Studies list will allow me to interrogate connections between works of science fiction such as /The Iron Heel/ and works of Utopian philosophy, such as Ernst Bloch's /The Principle of Hope/ and Frederic Jameson's /Archologies  of the Future/. XXX

My Future of the Book list will engage with the cultural and literary impact of digital platforms for the dissemination of information, and will be informed by book history, textual criticism, and the digital humanities. Foundational texts in book history by Adrian Johns Rodger Chartier will provide context for a theoretical examination of platforms and networks as they relate to cultural and social practices of reading. Particular attention will be given to considerations of open access in the academy, the influence of commercial platforms such as Amazon, and the advent of new approaches  such as digital social editions, public writing, and ebooks as applications.

The Victorian Science list is concerned with divergent visions of science in the 19th century, with particular attention to the aesthetics of science and perceived and real distinctions between science and pseudoscience. In the late 19th century, scientific theories and technological advances heavily influenced writers such as Charles Dickens, Wilkie Collins, Sir Arthur Conan Doyle, and Richard Marsh. Psychical phenomena such as mesmerism, the "Odic force," and mediumship were widely considered to be valid avenues of scientific exploration, and physiognomic disciplines such as phrenology were reaching their peak. These pseudoscientific branches of science provide material for an examination of scientistic practices, or the pursuit of a science based on aesthetics rather than epistemology. The representation of pseudoscience in 19th century literature also provides a point of reference for modern rhetorics of progress and futurity.
