#+TITLE: Victorian Science List
#+OPTIONS: num:nil 

**** Alioto, Anthony. /A History of Western Science/. (1992)
**** Altick, Richard. /Deadly encounters: Two Victorian Sensations./ (1986)
**** Arnold, David. "The colonial prison: Power, knowledge and penology in nineteenth century India." In /Subaltern studies/. (1994)
**** Baucom, Ian. /Out of place: Englishness, empire, and the locations of identity./ (1999)
**** Beer, Gillian. /Darwin's Plots/. (2009)
**** Blaise, Clark. /Time Lord: Sir Sandford Fleming and the Creation of Standard Time/. (2002)
**** Bowler, Peter J. /Evolution: The History of an Idea./ (1989)
**** Brantlinger, Patrick. /Rule of darkness: British literature and imperialism,1830–1914/. (1988)
**** Butler, Samuel. /Erewhon./ (1872)
**** Claussen, Christopher. "Sherlock Holmes, order and the late-Victorian mind." in /Georgia Review/ (1984)
**** Collins, Wilkie. /The Moonstone/. (1868)
**** Darwin, Charles. /The Origin of Species/. (1859)
**** DeWitt, Anne. /Moral Authority, Men of Science, and the Victorian Novel/. (2013)
**** Dickens, Charles. /Bleak House/. (1853)
**** Doyle, Arthur Conan. /The Adventures of Sherlock Holmes/. (--)
**** Doyle, Arthur Conan. /The Lost World/. (1912)
**** Harben, William. /The Land of the Changing Sun/. (1894)
**** Kohn, David. /The Darwinian Heritage/. (1985)
**** Lang, Andrew. /The Book of Dreams and Ghosts./. (1897)
**** Levine, George. /Darwin and the Novelists: Patterns of Science in Victorian Fiction./. 
**** Lightman, Bernard. /Victorian Science in Context/. (1997)
**** Marks, John M. /Science and the Making of the Modern World./ (1984)
**** Marsh, Richard. /The Beetle/. (1897)
**** Merritt, A. /The Moon Pool/. (1918)
**** Mill, John Stuart. /Autobiography/. (1873)
**** Moskowitz, Sam. /Science Fiction by Gaslight: A History and Anthology of Science Fiction in the Popular Magazines, 1891-1911/. (1974)
**** Murphy, Patricia, /In Science’S Shadow Literary Constructions of Late Victorian Women/. (2006)
**** Renk, Kathleen J. /Magic, Science, and Empire in Postcolonial Literature : The Alchemical Literary Imagination./ (2012)
**** Stevenson, Robert Louis. "The Strange Case of Dr. Jekyll and Mr. Hyde."
**** Stoker, Bram. /Dracula/. (1886)
**** Strick, James Edgar.	/Sparks of Life: Darwinism and the Victorian Debates over Spontaneous Generation/. (2000)
**** William Coleman, /Biology in the Nineteenth Century/. (1977)

