* questions
** How does the concept of aura apply (or not apply) in an age of digital, rather than mechanical,  reproduction?
Think about Kitler and the interchangability/fluidity of the digital
Do networks have aura?
With a (chemical) photograph, you feel a lack, a comparison with the painting. What lack do we feel with modern digital media? Thinking about ebooks, Facebook vs myspace, etc
Does vinyl have aura?
** Some of the writers on the list (Kirschenbaum) combine technical rigor with a humanistic sensibility. Others are more focused on one domain (Kitler and technology, McLuhan, many others on the human). Do you think there is a Two Cultures problem in new media discourse? How important is it to understand and/or reconcile technical detail and experiential or cultural understanding?
seems to be more room for the humanistic in the technical: chaos theory (kitler and gleick, conrad's game of life), quantam theory, AI and neural networks, etc all "problemetize the computaitonal model" (kitler intro)

Kitler: "drive the human from the humanities"
** How should we understand the process of encoding (relating to writing, cryptography, modern media theory)? Does it change our cognition? Is it colonial (Kitler and Dracula)?

** How do you characterize the word "digital"—historically, rhetorically, and practically? Is all writing digital (Bolter, Writing Spaces)? How does the digital intersect with the "marvelous" and the "wonderous" (Reading Writing Interfaces (Lori Emerson)?
Chartier reminds us that all writing has a material component, as does Pipes
** How important are distinctions between data and process (von Neuman architecture, J. L. Austin's /How to Do Things with Words/) Think about ebooks, games. Do these thigns exist without a human subject? Think also about object-oriented ontology (and state/method from object oriented programming)
* book notes
** literature, media, information systems (kitler)
*** intro
applies information theory (claude shannon) to new media questions

makes discourse analysis "high tech"

uses post-structuralist ideas, suggesting that technology was itself the blind spot of structuralism

in the age of computers, all information/media is interchangable; video, text, etc are just shallow choices on how to display

kitler uses example of airplane, in which the reality (inhospitable environment, complex flight systems) is hidden from users by friendly distractions
- kind of two worlds
- in america, there is no hacking/modding/repairing culture, so the difference is even more pronounced

notions of what an author is and how they are read are always histoically determined, aspects of a larger communications system
- literature can be treated as a form of data processing
- texts cannot be read independant of literary discouse; in order to make "sense" of literature, we need literary culture
- before rise of gramaphone, film, typewritier, literature had a monopoly on discouse networks. after, the materiality of literature could not be ignored. before, language had romantic/spiritual powers, but typewritier removes writing from sensuous hands. surrealism deals with mechanically writing down sense impressions, which makes sense for this moment**** Kitler, Friedrich., /Literature, Media, Information Systems/ (1997)
**** Lessig, Lawrence. /Remix: Making Commerce Thrive in the Hybrid Economy./ (2008)

**** Marshall McLuhan. /The Gutenberg Galaxy./ (1962)
**** Matthew Kirschenbaum. /Mechanisms: New Media and the Forensic Imagination./ (2008)
**** McGann, Jerome. /Radient Textuality./ (2004)
**** McKenzie, D. F. /Bibliography and the Sociology of Texts./ (1999)
**** Michel Foucault, /The Archaeology of Knowledge./ (1969) 
**** Piper, Andrew. /Book Was There: Reading in Electronic./ (2013 reprint)
**** Stallman, Richard. /Free Software Free Society./ (2009)
**** Stephen Ramsay. /Reading Machines: Toward an Algorithmic Criticism./ (2011)
**** Walter Ong, /Orality and Literacy: The Technologizing of the Word./ (1982)
**** Wolfgang Ernst. (Ed.) /Digital Memory and the Archive./ (2012)

*** Gramaphone, Film, Typewriter
Suggests that optical fiber networks are coming because they are the pentagon's hedge against the atomic bomb (weird)

Digitalization (sic) has made it so that voice and text have become mere effects on the surface or an interface for the consumer
- senses are "mere glitter"

what ended in bits began with writing
- writing is fundamentally a digital medium, it's a form of encoding

Chris Marker (film maker) writes: "They have put themselves in the place of my memory, they are my memory. I ask myself how people remember if they do not make movies, or photographs, or tapes, how mankind used to go about remembering"

notes some elegant distinctions about turing
- turing's handwriting sucked, and he imagined inventing a typewriter
- instead, he invents the computer, and his model is based on a ribbion, i.e. a string of editable instructions
*** dracula chapter

“We are bringing the plague, and they don’t even know it,” said Freud to Jung, as their ship moved into New York harbor. “This was the being I was helping to transfer to London, where, perhaps, for centuries to come he might, amongst its teeming millions, satiate his lust for blood, and create a new and ever-widening circle of semidemons” (52)

Kitler reads Dracula as a story of encoding
- blood is encoded and transmitted (two "bites" are passed on)
- stenography and typewriting features prominently

women have a choice: typewriter or vampirism

his larger theory is essentially that wars of the future are fought with information. Dracula is about a war of information, vampirism is communicated and the cure is the spread of textual information through mechanical means (stenography, typewriter)

Dracula is provintial, the hunters are democratic, cosmopolitan

** Track Changes (Kirschenbaum)
recovering obscured histories: women in early word precessing, quotidian word processing experiences, not just academic avant garde experiences

John Barth in Paris Review:
“Do you think word processors will change the style of writers to come?” Plimpton asks. “They may very well,” Barth replies, and continues: “But I remember a colleague of mine at Johns Hopkins, Professor Hugh Kenner, remarking that literature changed when writers began to compose on the typewriter. I raised my hand and said, ‘Professor Kenner, I still write with a fountain pen.’ And he said, ‘Never mind. You are breathing the air of literature that’s been written on the typewriter.’ So I suppose that my fiction will be word-processed by association, though I myself will not become a green-screener

Adam Bradley: did forensic analysis of Ralph Ellison's machine

Kenner, student of McLewhan, wrote /Mechanical Muse/ about how historical changes in writing process affected authors



nowadays business and commerce circulate in a algorithmic form that is indistringuishable from writing

fundamental thesis: "sometimes the details really do matter" and "this is an option Dickens did not have"

** Perfect
the word perfect describes the aspirations of word processing. it describes the sense of producing an absolutely finished product and the desire for efficiency and productivity

writing is never "off the grid." it is always a power technology--it encodes power, is able to project language across space and time

To write Baroque cycle, Stephenson first used longhand, then Emacs, then wrote a conversion program to Quark Express in Lisp to send to his publisher

great passage from Franzen about having to open his computer and stick a pencil in to stop an annoying whine
- Kirschenbaum: "No virtual realities here, only the minute torques and tolerances of the everyday: relative humidity, rubber bands, and stripped screws, their shavings of low-grade steel no doubt collecting somewhere inside the burlesque cavity of the machine’s exposed innards."
- sometimes the details really do matter



** Writing Spaces (David Bolter)
letter press the first word "processor"

technology comes from tekne, which is Greek for art or craft, so we should think of technology more broadly
- in /Phaedrus/, the alphabet is considered a tekne

literacy is realizing that language has a visual and not just an auditory or oral dimension
- in literary culture, writing is a part of our spoken communication, it affects how we speak, can use both colloquial and literary terms

computers are tangible objects, and thus are not excluded from materiality

computer writing is virtual, but so is writing in print
- all writing works within an abstract space of signs

** mechanisms (Kirschenbaum)
mechanism is both process and product
seems to be suggesting a close reading of technologies and artifacts

** materiality
forensic matreialty (from applied field of computer forensics)
formal materiality (manipulate symbols, not atoms)

not just distinctions between hardware and software, esp. because line is blurring between those

alleographic vs autographic
alleographics = reproducable
autographic = reproduction betrays ontology/nature of work

** case studies
agrippa (william gibson)

** comparative textual media (hales and jessica pressman)
materially-oriented approach
exploring alternative pratices
functions at different scales, tries to be a framework that works in many different environment
*** interesting
"big humanities"
*** follow up
tree of codes
only revolutions

John Barth: "Coming soon!!!" about man obsessed with hypertext, ordered in hardcover for the grinder

/The Mechanic Muse/ (Kenner)

* speech
Pick up a modern book. This one will do: the one you are looking at right now.

* talk with matt
add new matt kirsxhenvaum book
* areas:
** book history/bibliography
** early hypertext theory
(boulter, benkler, mcgann)

** interfaces/platforms
Emerson, Textual Media
** books and freedom

talk about the levels on which we engage with books

- as object
- as social construct

text
- text as locus of interpretation ("There is nothing outside of the text." Derrida)
- text as encoded data, the subject of computation (Moretti, Jockers)
- text as object 


positivism in bibliography

- relate to positivism in digital humanities[[file:~/1][file:~/1]]

* concepts

** literature is the fragment of fragments
goethe
means that only a tiny portion of history or occurances makes it into literature


* references for hacksessability article
look up /The Visible Word/, Johanna Drucker
