* book notes
** Book Was There (Andrew Piper)
reading isn't just an escape, it's a disciple
- reading molds the reader

he was not only a reader but a computer user

says he wasn't a great reader, in the grand sense of Sartre or Goethe

are new digital natives too far the other way (i.e., not reading?)

book tries to bridge the divide between book hisotry and media studies
- written more as a classical essay, not a jeremiad or a highly theoretical work (thank you)

"I can imagine a world without books. I cannot imagine one without reading."

gripes about too much screen reading is quite similar to gripes about too many romances (Don Quixote) or two many penny dreadfuls

"books will always be there"
- but it is our choice where books will be

books allow us to reflect on who we once were and who we want to be

chapter 1: starts with the conversion of St. Augustine, he's in a garden filled with doubts and hears a child from another house singing "take it and read"
- after reading one passage he is converted
- use of the codex as technology: he picks up the book and picks a random passage, he walks away with his finger marking the passage
- the graspability of the book, in a material as well as spiritual sense
- the book is /at hand/
  - book of hours (graspable)
  - manual
  - manicule
  - braile

books are things that hold things
- encapsulation

books are also menat not to be grasped
- they lie around
- you let them go, to let them circulate

So how do we "hold onto" digital books?
- Text Rain - art in which text falls on a screen into open hands 

digital texts are marked by a weak sense of closure

yet touch has emerged as a mode of interaction with the digital

we are afraid of reading's inertia
- we whisk away at the scree,
- skimming is the new normal

Chapter 2: Faces

interfaces
looking and reading
frontispiece

Lavater: created a book of faces designed to allow people to learn to divine the soul in the face
- started the craze for silhouettes in the 18th century as well as prefigured Lombroso, phrenology

crampedness of the face of the webcam
- captures a sense of compression

we sleepwalk through the web
- we are mentally asleep but physically awake

Facebook is the "new narsessystem"

Chapter 3: The page

Ebooks are single pages

"There is just too much stuff on the screen now"
- distraction
- refrain that we're in an age of distracted readers, people can't finish a book
- Pliny: "read much, not many" (anxieties about shallow reading go way back)

the medeval page was a cacophony

doesn't think enhanced ebooks are the way
- we need to think about the architecture of the text, not the technology

fenestration: the act of looking /through/ the page

could be written of the page (from Susan Orlean and /Orchid Thief/: 
- "there are too many ideas and things and people. Too many directions to go. I was starting to believe the reason it matters to care passionately about something, is that it whittles the world down to a more manageable size." <---- this
- pages are signs of passion, they are the result of whittling down, chipping away

"pages are material arguments of individualization" 
"pages are finite"
pages allow us to access the world at random

the quotation mark was invented in Frane a century before in England (fun fact)

the book of nature
- the book can be a faithful reflection of nature
- nature is like a book

the digital makes reading nomadic rather than domestic
- instead of curling up with a book, we roam across a plain (or traverse a superhighway)

reading assume topology
- the stream is chronological, not topological
- you can never step in the same stream twice. there is no rereading

Goethe: "It would be a lowly art that allowed itself to be understood all at once"

** Reassembling the Social (Bruno Latur)
explores Actor Network Theory, a take on sociology that includes non-human entities in the social graph
- differences in relations with humans and animals should be explored in the relationship, rather than being presupposed
- technologies and objects also in graph
- seems to me like a play to allow social science to include science
** Emergence of the Digital Humanities (Steven Jones)
thesis is that the eversion provides an essential context for examining DH as a new fieod of study

book is about the digital humanities
- new tradition of the digital humanities

burst dot com bubble was the end of the old cyberspace era

2005: Blackwell's Companion to DH
2006: NEH grants for DH
- DH emerged in these years

he's into the eversion, which comes from Gibson

** Reading Writing Interfaces (Lori Emerson)
"this book begins and ends with magic"
we are in the era of the marvelous
- ipad, google glass seem to have supernatural properties

book is about demystifying technology
- the interfaces are actually becoming harder to percieve due to the seductions of modern technology
in computing, interface refers to the point of interaction between hardware and software components
- many kinds of interfaces, 8 interfaces include hardware to hardware, hardware to software, human to hardware

the idea of the book is to find out what is revealed by what is concealed
- the book is about magic in the sense of the wonderous and magic in the sense of obscured complexity
- the glossy surface alienates the user

"when transparency...becomes and unuestioned necessity," all computing devices then only become tools for the consumption of content

"the definition of ideology is that which we are not aware of"

refrences Kitler, who says "media determine our situation"

media archology does not seek to reveal the present as an inevitable product of the past
- similar to m. kirchenbaums use of referse chronology to avoid the Sonderweg fallacy

** Literature, Media, Information Systems (Kitler)
*** intro
applies information theory (claude shannon) to new media questions

makes discourse analysis "high tech"

uses post-structuralist ideas, suggesting that technology was itself the blind spot of structuralism

in the age of computers, all information/media is interchangable; video, text, etc are just shallow choices on how to display

kitler uses example of airplane, in which the reality (inhospitable environment, complex flight systems) is hidden from users by friendly distractions
- kind of two worlds
- in america, there is no hacking/modding/repairing culture, so the difference is even more pronounced

notions of what an author is and how they are read are always histoically determined, aspects of a larger communications system
- literature can be treated as a form of data processing
- texts cannot be read independant of literary discouse; in order to make "sense" of literature, we need literary culture
- before rise of gramaphone, film, typewritier, literature had a monopoly on discouse networks. after, the materiality of literature could not be ignored. before, language had romantic/spiritual powers, but typewritier removes writing from sensuous hands. surrealism deals with mechanically writing down sense impressions, which makes sense for this moment**** Kitler, Friedrich., /Literature, Media, Information Systems/ (1997)
*** Gramaphone, Film, Typewriter
Suggests that optical fiber networks are coming because they are the pentagon's hedge against the atomic bomb (weird)

Digitalization (sic) has made it so that voice and text have become mere effects on the surface or an interface for the consumer
- senses are "mere glitter"

what ended in bits began with writing
- writing is fundamentally a digital medium, it's a form of encoding

Chris Marker (film maker) writes: "They have put themselves in the place of my memory, they are my memory. I ask myself how people remember if they do not make movies, or photographs, or tapes, how mankind used to go about remembering"

notes some elegant distinctions about turing
- turing's handwriting sucked, and he imagined inventing a typewriter
- instead, he invents the computer, and his model is based on a ribbion, i.e. a string of editable instructions
*** dracula chapter

“We are bringing the plague, and they don’t even know it,” said Freud to Jung, as their ship moved into New York harbor. “This was the being I was helping to transfer to London, where, perhaps, for centuries to come he might, amongst its teeming millions, satiate his lust for blood, and create a new and ever-widening circle of semidemons” (52)

Kitler reads Dracula as a story of encoding
- blood is encoded and transmitted (two "bites" are passed on)
- stenography and typewriting features prominently

women have a choice: typewriter or vampirism

his larger theory is essentially that wars of the future are fought with information. Dracula is about a war of information, vampirism is communicated and the cure is the spread of textual information through mechanical means (stenography, typewriter)

Dracula is provintial, the hunters are democratic, cosmopolitan

** Track Changes (Kirschenbaum)
recovering obscured histories: women in early word precessing, quotidian word processing experiences, not just academic avant garde experiences

John Barth in Paris Review:
“Do you think word processors will change the style of writers to come?” Plimpton asks. “They may very well,” Barth replies, and continues: “But I remember a colleague of mine at Johns Hopkins, Professor Hugh Kenner, remarking that literature changed when writers began to compose on the typewriter. I raised my hand and said, ‘Professor Kenner, I still write with a fountain pen.’ And he said, ‘Never mind. You are breathing the air of literature that’s been written on the typewriter.’ So I suppose that my fiction will be word-processed by association, though I myself will not become a green-screener

Adam Bradley: did forensic analysis of Ralph Ellison's machine

Kenner, student of McLewhan, wrote /Mechanical Muse/ about how historical changes in writing process affected authors



nowadays business and commerce circulate in a algorithmic form that is indistringuishable from writing

fundamental thesis: "sometimes the details really do matter" and "this is an option Dickens did not have"

*** Perfect
the word perfect describes the aspirations of word processing. it describes the sense of producing an absolutely finished product and the desire for efficiency and productivity

writing is never "off the grid." it is always a power technology--it encodes power, is able to project language across space and time

To write Baroque cycle, Stephenson first used longhand, then Emacs, then wrote a conversion program to Quark Express in Lisp to send to his publisher

great passage from Franzen about having to open his computer and stick a pencil in to stop an annoying whine
- Kirschenbaum: "No virtual realities here, only the minute torques and tolerances of the everyday: relative humidity, rubber bands, and stripped screws, their shavings of low-grade steel no doubt collecting somewhere inside the burlesque cavity of the machine’s exposed innards."
- sometimes the details really do matter
*** sci fi writers = early adopters

Douglas Adas
- early adopter of word processing and early computers
- collaborated with infocom on hitchhiker's guide interactive fiction
- bucked trend of iagining computers being conduits for AI and isntead iagined the hitchhiker's guide, which is essentially an ebook

jack vance
- early adopter of accessibile technologies, used speech snythesizer and large font due to deteriorating eyesight

William Gibson
- couldn't afford a typewriter for neuromancer
- imagined cyberspace, a consentual hallucination
- his ignorance of computers was actually an asset in imagining cyberspace, allowed him to romanticize the computer
- collaborated with Sterling on The Difference Engline, used word processing to fully collaborate

"it's not the scientists but the word people that have taken them (computers) up"

** Writing Spaces (David Bolter)
letter press the first word "processor"

technology comes from tekne, which is Greek for art or craft, so we should think of technology more broadly
- in /Phaedrus/, the alphabet is considered a tekne

literacy is realizing that language has a visual and not just an auditory or oral dimension
- in literary culture, writing is a part of our spoken communication, it affects how we speak, can use both colloquial and literary terms

computers are tangible objects, and thus are not excluded from materiality

computer writing is virtual, but so is writing in print
- all writing works within an abstract space of signs

** mechanisms (Kirschenbaum)
mechanism is both process and product
seems to be suggesting a close reading of technologies and artifacts

** materiality
forensic matreialty (from applied field of computer forensics)
formal materiality (manipulate symbols, not atoms)

not just distinctions between hardware and software, esp. because line is blurring between those

alleographic vs autographic
alleographics = reproducable
autographic = reproduction betrays ontology/nature of work

** case studies
agrippa (william gibson)

** comparative textual media (hales and jessica pressman)
materially-oriented approach
exploring alternative pratices
functions at different scales, tries to be a framework that works in many different environment
*** interesting
"big humanities"
*** follow up
tree of codes
only revolutions

John Barth: "Coming soon!!!" about man obsessed with hypertext, ordered in hardcover for the grinder

/The Mechanic Muse/ (Kenner)

* questions
- There is a rhetoric of progress that applies particularly to technology and the emergence of new media that suggests that present technology is an inevitable product of past technology. Why should we be suspicious of this rhetoric? What trends are not progress but "retrograde movement" (to use a military euphemism)? Are there points of inflection in which technology was at an "Anderweg," another path that it could have taken? Thinking about Nelson's /Dream Machines/, Stallman's /Free Software, Free Society/, Emerson's /Reading Writing Interfaces/.
- How does the concept of aura apply (or not apply) in an age of digital, rather than mechanical,  reproduction?
Think about Kitler and the interchangability/fluidity of the digital
Do networks have aura?
With a (chemical) photograph, you feel a lack, a comparison with the painting. What lack do we feel with modern digital media? Thinking about ebooks, Facebook vs myspace, etc
Does vinyl have aura?
- Some of the writers on the list (Kirschenbaum) combine technical rigor with a humanistic sensibility. Others are more focused on one domain (Kitler and technology, McLuhan, many others on the human). Do you think there is a Two Cultures problem in new media discourse? How important is it to understand and/or reconcile technical detail and experiential or cultural understanding?
seems to be more room for the humanistic in the technical: chaos theory (kitler and gleick, conrad's game of life), quantam theory, AI and neural networks, etc all "problemetize the computaitonal model" (kitler intro)

Kitler: "drive the human from the humanities"
- How should we understand the process of encoding (relating to writing, cryptography, modern media theory)? Does it change our cognition? Is it colonial (Kitler and Dracula)?

- How do you characterize the word "digital"—historically, rhetorically, and practically? Is all writing digital (Bolter, Writing Spaces)? How does the digital intersect with the "marvelous" and the "wonderous" (Reading Writing Interfaces (Lori Emerson)?
Chartier reminds us that all writing has a material component, as does Pipes
- How important are distinctions between data and process (von Neuman architecture, J. L. Austin's /How to Do Things with Words/) Think about ebooks, games. Do these thigns exist without a human subject? Think also about object-oriented ontology (and state/method from object oriented programming)
Are we becoming less literature? How does rading interact with ouur cognition? What is the relationship between books and screens? (/Book Was There/

What is the position of hypertext fiction? Comeback?

What is the relationship between digital humanities and new media studies?

How do ideas from book history such as patronage affect the modern writing, publishing, and consumption of texts?  and How does the form still constrain the production of meaning and its dissemination? Forms and Meanings (Chartier)
- what is the modern equivelant of the dedication?
- how do online communities of practice and heterodox hermaneutics affect the consumption of works? thinking of /Homestuck/ and /Undertale/. This literature is an event, it cannot be archived, unlike the Agrippa files, which has largely been archived.

* speech
Pick up a modern book. This one will do: the one you are looking at right now.

* talk with matt
add new matt kirsxhenvaum book
* areas:
** book history/bibliography
** early hypertext theory
(boulter, benkler, mcgann)

** interfaces/platforms
Emerson, Textual Media
** books and freedom

talk about the levels on which we engage with books

- as object
- as social construct

text
- text as locus of interpretation ("There is nothing outside of the text." Derrida)
- text as encoded data, the subject of computation (Moretti, Jockers)
- text as object 


positivism in bibliography

- relate to positivism in digital humanities[[file:~/1][file:~/1]]

* concepts

** literature is the fragment of fragments
goethe
means that only a tiny portion of history or occurances makes it into literature


* references for hacksessability article
look up /The Visible Word/, Johanna Drucker
