** literature, media, information systems (kitler)
in the age of computers, all information/media is interchangable; video, text, etc are just shallow choices on how to display

kitler uses example of airplane, in which the reality (inhospitable environment, complex flight systems) is hidden from users by friendly distractions
- kind of two worlds
- in america, there is no hacking/modding/repairing culture, so the difference is even more pronounced

notions of what an author is and how they are read are always histoically determined, aspects of a larger communications system
- literature can be treated as a form of data processing
- texts cannot be read independant of literary discouse; in order to make "sense" of literature, we need literary culture
- before rise of gramaphone, film, typewritier, literature had a monopoly on discouse networks. after, the materiality of literature could not be ignored. before, language had romantic/spiritual powers, but typewritier removes writing from sensuous hands. surrealism deals with mechanically writing down sense impressions, which makes sense for this moment**** Kitler, Friedrich., /Literature, Media, Information Systems/ (1997)
**** Lessig, Lawrence. /Remix: Making Commerce Thrive in the Hybrid Economy./ (2008)

**** Marshall McLuhan. /The Gutenberg Galaxy./ (1962)
**** Matthew Kirschenbaum. /Mechanisms: New Media and the Forensic Imagination./ (2008)
**** McGann, Jerome. /Radient Textuality./ (2004)
**** McKenzie, D. F. /Bibliography and the Sociology of Texts./ (1999)
**** Michel Foucault, /The Archaeology of Knowledge./ (1969) 
**** Piper, Andrew. /Book Was There: Reading in Electronic./ (2013 reprint)
**** Stallman, Richard. /Free Software Free Society./ (2009)
**** Stephen Ramsay. /Reading Machines: Toward an Algorithmic Criticism./ (2011)
**** Walter Ong, /Orality and Literacy: The Technologizing of the Word./ (1982)
**** Wolfgang Ernst. (Ed.) /Digital Memory and the Archive./ (2012)

** mechanisms
mechanism is both process and product
seems to be suggesting a close reading of technologies and artifacts

** materiality
forensic matreialty (from applied field of computer forensics)
formal materiality (manipulate symbols, not atoms)

not just distinctions between hardware and software, esp. because line is blurring between those

alleographic vs autographic
alleographics = reproducable
autographic = reproduction betrays ontology/nature of work

** case studies
agrippa (william gibson)

** comparative textual media (hales and jessica pressman)
materially-oriented approach
exploring alternative pratices
functions at different scales, tries to be a framework that works in many different environment
*** interesting
"big humanities"
*** follow up
tree of codes
only revolutions

* speech
Pick up a modern book. This one will do: the one you are looking at right now.

* talk with matt
add new matt kirsxhenvaum book
* areas:
book history/bibliography (technological determinism)
early hypertext theory (boulter, benkler, mcgann)
text
interfaces/platforms (emerson, textual media)
books and freedom

talk about the levels on which we engage with books

- as object
- as social construct

text
- text as locus of interpretation ("There is nothing outside of the text." Derrida)
- text as encoded data, the subject of computation (Moretti, Jockers)
- text as object 


positivism in bibliography

- relate to positivism in digital humanities[[file:~/1][file:~/1]]




