
* Forms by Carline Levine
Do forms constrain?
Forms provide affordances, shape how we approach problems and discourses

** Forms about patters
Forms can operate at differnt scales (i.e., genre and syntax)
Forms can persist across periods and cultures, or can be confined to particular places and times
Political structueres can move or be portrayed in a novel, becoming aesthetic forms

** Structuralism
Human discourse orgnaized into universal structures
Uses binary oppisitions (light/dark, male/female) as organizing principles
Binaries are a convenient form

** Affordances
Formalists say: forms matter
Forms shape what can be said and done in particular contexts == affordances
Afforcances comes from design theory
Rymes afford memory, repitton
Networks afford ciruclation
Sonnet highlight single idea or experience
Forms can only do so much, but can be expanded or leveraged in ways that push the form
Forms share one affordance: they're iterative and portable 
No form operates in isolation

** Conflicts between forms
Combinations of forms can be generative, unexpected
Example: biological clock meets tenure clock
Forms overlap--narrative affects poliitcal reality (prisioner can get pardon after new interpretation of crime), political reality affects narrative

** Too capacious?
Are they experiences that arent' forms? (says yes, interstices etc)
Do we spend too much time breaking down forms, ignoring what they actually do and afford?
Scholars look for the formless (hybridity, liminality)
  >> but we need orgnaizing principles, can't get rid of forms ultimately
"one cannot make a poem out of soup or a panopticon out of wool"
a prision is both a thing and a form, created from the affordances of metal and stone while remaining an abstract concept that can be applied across contexts

** Differences (and affordances) between theoretical forms
New Critics forcused on aesthetic form, ignored how it was shaped by political forms
Language of hermaneutics strong for aesthetic forms, weak for the granular assessment of political forms

forms are notentirely outgrowths of partcicularity 
Mark Schneiberg >> "it is preci\sely the endurance of holdover forms that can make a society suprisingly plural"


Both New Formalists and genre theory could benefit from attention to the long sotry of forms, their movement across time and space

forms and genre are not just synonymous (though many they seem so)

genre is commercial and historical, a taxonomy
forms can orgnaize both social and literary objects, are patterns...not really subject to interpretation and debate, since not strictly pegged to a term
>>>form is recognition, genre is labeling?

** What's missing from the Marxist tradition?
Marxists argue that forms blind us to a reality that always exceeds form
Conventional narratives inure people to lives led within exploitative and hierarchical system ("as social subjects")
Marxism assumes that the political (form) is always the root or ground of the aesthetic (form)

Example: Tom Brown's School Days
>>> uses Bildungroman and gender binary forms (aesthetic form meets political form)
both narrative and gender attempt to impose their own shape on the text
"rather than tracking the buried 'content' of the form, I propose here to track the forms of the content"
*** Thesis statement
We don’t know which came first. What we do know is that both the literary and the social form—Bildung and the gender binary—preexist the text in question. Both move from other sites into this text, carrying their own ways of organizing experience with them. While we might speculate about which form is primary, or about Hughes’s own motivations, the text itself shows us something interesting about what happens when narrative form encounters the gender binary and the two begin to operate together. In fact, a predictable, generalizable hypothesis about form unfolds from this collision, regardless of the author’s intentions or the origins of either form. As long as pliability—the susceptibility to development—falls on the feminine side of the gender binary, the Bildungsroman will have to be a feminine genre, even when its protagonists are male.Most Marxist formalist critics would approach the narrative form of Tom Brown’s Schooldays as the working out of an ideological position or as an “abstract of social relationships.”33 Most politically minded new formalists would read the text as a response to the immediate social world around it. The formalism that emerges here is different: I read narrative and gender as two distinct forms, each striving to impose its own order, both traveling from other places to the text in question, and neither automatically prior or dominant. One might say that I am flipping White’s terms upside down: rather than hunting for the buried content of the form, I propose here to track the forms of the content, the many organizing principles that encounter one another inside as well as outside of the literary text. Instead of assuming that social forms are the grounds or causes of literary forms, and instead of imagining that a literary text has a form, this book asks two unfamiliar questions: what does each form afford, and what happens when forms meet?


instread of 

** Not so simple
In theory, politics determines our place
In practice, so many conflicting forms exist (narrative, political, etc) that our environment is necessarily complex

makes the case that no form, no matter how seemingly powerful, dominates all others
"But at the same time I would argue that an exclusive focus on ultimate causality has not necessarily benefited leftist politics. It has distracted us from thinking strategically about how best to deploy multiple forms for political ends."

** Narrative 
Best captures the experience of colliding forms
Present causality as a sequence of events rather than positing an originary cause (i.e., more accepting of diverse forms rather than some dominant cause or superstructure, a "conjoining" rather than a "necessary" connection
Defends her use of paraphrase

** Organizing forms of book
Whole, Rhythm, Hierarchy, Network
*** Will look at:
**** Order imposed by each form
**** How are scholars dependant on organizing forms?
**** Relationship between literary and social forms
**** How new appraoch to multifaced forms would work
* Principles of Hope
People have always dreamed of this,ndreamed of the better life that might be possible. Everybody's life is pervadedby daydreams: one part of this is just stale, even enervating escapism, evenbooty for swindlers, but another part is provocative, is not content just to accept the bad which exists, does not accept renunciation. This other parthas hoping at its core, and is teachable. It can be extricated from theunregulated daydream and from its sly misuse, can be activated undimmed.Nobody has ever lived without daydreams, but it is a question of knowingthem deeper and deeper and in this way keeping them trained unerringly,usefully, on what is right. Let the daydreams grow even fuller, since thismeans they are enriching themselves around the sober glance; not in the sense of clogging, but of becoming clear. Not in the sense of merely contemplative reason which takes things as they are and as they stand, but of participating reason which takes them as they go, and therefore also as they could go better.

this world is a world of repetition  or of the great Time-and-Again; it is a palace of fateful events, as Leibniz called it without breaking out of it. Occurrence becomes history, knowledge re-remembering, celebration the observance of something that has been. This is how all previous philosophers went about it, with their form, idea or substance posited as being finished, even postulating Kant, even dialectical Hegel. In this way physical and metaphysical need spoiled its appetite, in particular its paths

* Tenses of Imagination 
Three kinds of science fiction:
Space Anthropology, Utopia, and Putropia
Prefers space anthropology, more uniquely human
Putropia, a breaking down of a utopia

* News from Nowhere (William Morris)
Anarchist utopia
Labor is voluntary
Fear of a work shortage, i.e. work is so pleasureable that people fear they will run short of it
parliment used to store manure
no politics (one-page chapters on "no politics")

There are four characteristic types of alternative reality, he argues: the 
***  paradise or hell
often reached via a journey, but they journey (space or sea or time) is not important. the type of place is, rather, largely unchanged

paradise and hell only rarely utopian/dystopian

"ordinarily the projections of a magical or religious consciousness" 97

garden of eden is only latently utopian - utopian for Williams seems to imply realizibility

often just played for sensation, may be utopian if more connected to real questions of soceity, but mostly isn't

*** the positively or negatively externally altered world
can often be the result of scientific perspectives, either as explaining prinicples of nature that brought about the change or by a growing understanding of science in a society

"either falls short or goes beyond" utopian and dystopian mode 97

often limits or anuls human achivement, and so tends toward the dystopian
even when utopian, the lack of agency must be taken into considerations (as in Wells' /Day of the Comet/)

*** the willed transformation
"inspired by the scientific spirit" seems to conflate this with the next category a bit. kind of seems like this should be throught of more generally, i.e. utpias based on religion like "left behind." mentions that the scientific spirit can be subordinate to revolutionary or pastoral tendencies, though there seem to be instances of this type that don't really include science
*** the positive or negative technological transformation

brings up Engel's distinction between "utopian" and "scienntific" socialism (the latter is based on a "scientific" analysis of history that makes communism the inevitable product of capitalism)

Bacon's /New Atlantis/ is scientific, More's /Utopian/ is utopian

*** Readings of sci fi

Looking Backward - capatilistic monopoly is next stage of development, oraching rationalism "a work without desire", Williams quotes Morris's critique that Bellamy can't see any alternatives to macinary of status quo and so extrapolates on them
brave new world - "confused" combination of socialism and capitalistic corporatism
dispossed (le guin) - Williams says it's interesting becaus it can explore the utopian and the non-utopian option simultaneously, unlike in /news from nowhere/ or /looking backward/ which use the dream as their "portal". Has "wary acceptance" of  utopain goals and also the realisation that a utopain state can be achived by a few through non-utopian means. I agree with Williams that it's a product of its time (the '70s), made me think of /Woman at the Edge of Time/

*** tenses of utopia (essay)

shows his like for space anthopooogy once again, he's writing about le guin's /dispossesed/

heuristic vs. systematic utopa

heuristic can be too sentimental - /News from Nowhere/ an example of this, also Hyhnamland
systematics can get too into the weeds, can't see ny real life happening there

we do not write alone, writing is a product of synthesis
imagination is not imagination, "it feels like contact"
the process is not distillation or asociation, but formation "you feel your way into", NOT like imagination
 >>> seems to indicate that it's a new thing, but formed of old things

reconstructing the past or the future through this process of formation requires generating a type of "feeling," i.e. a real understanding of the situation (such as infantacide or other unthinkable things) that regards it not only as a foreign or strange thing, but as something that can really be contempated and realiszed

"dispossed" an example of this, not just a systematic look at a new society but a "feeling" exploration of that society

*** passage
In any real future tense, then, what we call imagination seems more like
the usual accounts of it than in either present or past tenses. We speculate,
we project, we attempt to divine, we figure. The actual writing that goes
with that dimension is in its turn distinctive: more general; more imme-
diately accessible to ideas; often more angular and more edged; relatively
low in the kind of saturation by detailed and unlooked-for experiences
so common and ordinarily so valued in the other tenses. I do not want
to turn a contrast of kinds into some order of merit. Each kind of writing
does quite different work. But if that is a recognizable kind of imagina-
tion – over a range from the secular and political to the solidly traditional
and the surprisingly private visions and divinations – there is a problem in
using not just the same word but the same concept, pointing to the same
general process, in the other tenses. The problem is already there, however,
in the everyday range of the word. The mental concept of something not
present to the senses, which corresponds to future-writing and to many
kinds of fantasy, coexists in the language with the sense of empathy, of feel-
ing our way into a situation which in a general way we know but which we
can come to know as it were from the inside – a sense which I think is not
far from the idea of discovering and being moved by a structure of feel-
ing within what is already nominally and even carefully known. Yet if the
word can be applied to either process, the real processes are still different,
and the key difference, as it matters in writing, seems to me essentially a
matter of real tense. (123)

* To read
Wells /Day of the Comet/
/The Coming Race/
demand the impossible


* commonplace

** tenses of imagination

But now, very clearly, there are other deeper forces at work, which perhaps only imagination, in its full processes, can touch and reach and recognize and embody. If we see this, we usually still hesitate between tenses: between knowing in new ways the structures of feeling that have directed and now hold us, and finding in new ways the shape of an alternative, a future, that can be genuinely imagined and hope- fully lived. There are many other kinds of writing in society, but these now – of past and present and future – are close and urgent, challenging many of us to try both to understand and to attempt them.
