* short outlines 
** Seven Beauties (C-Ronay)
- "technoscience"
- "science fictionality" - seeing the world and testing expereince as if it were science fiction. we view events as if they happen to us.
- SF has not grown into the world, the world has grown into SF
- "fictive neology" - new words the seperate the new world from our own. they are "knots of estrangement"
-"technoscientific sublime" - a response of awe and dread to advances that escape the bonds of their human creators, such as the atom bomb or gene modification
- science fictional grotesque - collapose of ontological categories producing a response of fascination and hooror. a spectacle of monsterous fusions.
- the technologiad - moalizes modern technology and contextualizes it
- SF asks readers to be more expansive and more limited than they already are
- traces gaps in science fiction (gaps of plausibility and morality)
- SF posits that anything in the natural world can have an artificial analogue and can therefore be transformed (Accelerando takes this to logical conclusion)


** History of Utopian Thought (Herzler)
 religous utopias
- examines prophets starting with Amos
- prophets look for vindication on earth (immanence, or God's presence on earth))
-  apocalyptists look for vindication in heaven (transcendence), no edification to be found in apocalyptic texts
- John: seven days of work, day of rest, then infitiy (8th day), each day is 1000 years

the role of the apocalyptist is to predict the overthrow of evil forces and the triumph of godly forces
- marx could be considered to fit this mold. marx suggests that he is a product of the forces that he is predicting, the future is reaching back (like prophet or apo)




* Definitions of Science Fiction
Darko Suven - SF is characterized by cognitve estrangement represented by a novum

Broderick - science fiction is defined by use metanym, i.e. each characteristic represents a different kind of reflected world. spaceships = space opera. SF is also concerned with object rather than subject

Samuel R. Delany - SF is a symbolic genre, it deploys a wide variety of material symbols that each have their own associations

SF is about distance? has to be close enough but not too close to realism, based on the novum.

the dialating door


* history of utopian thought (herzler)
- the prophets look for Jehovah's vindication on earth. (like imminence)
- the apocolyptists look for vindication in heaven (like transcendence)

John: seven days of work, day of rest, then infitiy (8th day), each day is 1000 years

the goal of an apocalyptist is to predict the overthrow of evil forces and the triumph of godly forces
- seems similar to Marx, self-fulfilling prohpecy..but maybe more interesting to think of it as a future reaching back and into the prophet's present. with Marx, the forces he predicted seemed to be influencing the creation of his tract. prophecy is kind of bi-directional

Herzler considers Apocalyptists "almost useless" from the socilogical point of view, simpler and more emotional than the prophets: "if one goes to apocalyptic literature for edification one does not get it"

considers Jesus a "great nature" formed not by circumstances but from within

** "pseudo-utopias"
** conclusions
in "the utopians and their utopias" he suggests that people are divided into three categories, each favoring eithe rthe past, present, or future. past dwellers are reactionary, present dwellers are complacent, and those that consider the future he considers utopians and largely lauds

morality and the state tend to become static and decadant, utopians are a force that resists the extravegance of these institutions

utopians are critics of their age

believes that geniuses are those who are less bound by the constraints of their time

utopians feel the Zeitgeist and yet are dominated by the Weltschmertz




* Utopia and the Ideal Society (Davis)
concerned with the utopian early modern fixation on idleness, says works like more's utopia and burton (/Anatomy of Melancoly/) were partly reponsible for the development of bureacracy that made humanity part of a human machine

bacon imagined a utopia based on plenty from industry

most utopians after more focus on self-moderation

* Empire (Hardt and Negri)
sovereignty has declined, replaced by a new sovereignty

imperialism was the extension of european nation states beyond their own boundaries

old system was imperialism, calls the new system Empire

capital now exists in a "smooth world", suggesting homoginization and lack of real boundaries

Empire does not only manage a territory and a population, but also creates the world it inhabits. It doesn't just regulate human interaction but rules over human nature

building on Foucault's idea of "biopower" (and biopolitics)

Empire is a postmodern construct that is based on control of bodies, globalization, switch from international conflict to attack on a criminal within the system (terrorist)

* red planet
uses the metaphor of bossing (metalworking process that leaves the impression of the shaped metal on a bag) to describe the relationship between the work of SF and the milieu in which it is created...there is a "negative space" based on the author's world that is used in the process of creation
- this negative space is often bound by the structures and limits of capital (since the finished product does not usually attempt to address the totality of capital explicitly)

Verne's 20,000 Leagues Under the Sea
- subject of verne's novels is man's domination of nature (point first argued by Pierre Macherey)
- creatures and natural locations are specifically commodotized, given actual price values
- nemo's crewmen speak their own language, effacing their origins

Matrix
- reads matrix as appropriating multiculturalaism, engaging in a kind of universaility that maintains distance and superiority
- firm invites a hermaneutic/allegorical reading, but names like neo, trinity, morpheus frustrate such readings
- film is simply another allegory of late capital, a machine perpetuating itself and running out of any control...we are all colonies, no longer any colonizer

reads 20,000 Leagues and Matrix not in themselves, but in the negative space (the "shot bag" that is left after the process of bossing) that they leave behind. what assumptions of capital underlie these works?

book is a reaction to the "suven event"

* crusing utopia (2009, José Esteban Muñoz)
this book is fundamentally a reaction against political pessimism, nihilism, post-structuralism that the author percieves as anti-utopian and all-too-prevelant in the academy

wants to talk more about potentiality than then concrete present

he's looking at the past to critique a present that is closing off the future

his idea of cruising isn't just (or even mostly) about cruising for sex, he is interested in cruising as a description of exploring potentialities...he challenges reader not only to reexplore old ideas but also to "fell hope and feel utopia"

aligns himself with anti-anti-relationality
-anti-relationality is Lee Edelman's (No Future) idea that queerness stands resistant to the patriarchal lynchpin of the child. Munoz thinks this idea is too totalizinng and itself becomes privelaged, anti-relationity is usually associated with male-male abandon or some kind of more streaightofward LGBTness. His example of anti-anti-relationlity is from Eileen Miles's /Chelsea Girls/j and describes the relationship between an old white man and the young lesbian who is his caretaker

"queerness is in the horizon" - the focus on a concrete LBGT movement in the present ignores the larger issue of potentiality...if queerness is assimilated, it ignores the long tradition of queerness as an outsider force

engages with Ernst Bloch's Principles of Hope

"hope .. is both a critical affect and a methodology" > methodology combats force of political pessimism and resists anti-utopianism
- using hope as a critical methodology works as "a backward glance that enacts a future vision

"queerness is not here. Queerness is an ideality. Put another way, we are not yet queer. We may never touch queerness, but we can feel it as the warm horizon of a future imbued with potentiality. We have never been queer, yet queerness exists for us as an ideality that can be distilled from the past and used to imagine a future. The future is queerness's domain"

performing astonishment
- draws the idea of "performing astonishment" from bloch, Warhol an example with "wow," "gee"n
- "Astonishment helps one surpass the limitations of an alienating presentness and allows one to see a different time and place"
- utopia exists in the quotidian, uses the example of Warhol's coke bottle art...the queer artist can detect "an opening and indeterminacy" in what is otherwise just an example of consumerist alienation

invokes J.L. Austin's /How to Do Things with Words/ as a point of resistance to the western idea that thigns are real or idealized...instead, Austin uses the idea of felicitous and infelicitous language (felicitous language DOES thigns)

* dark horizons (moylan and bacolini)
distinguishes between the dystopian and the anti-utopian: dystopia is social dreaming like utopia, anti-utopia specifically rails against or rejects the imaginative project of utopia

dystopia uses its own set of formal strategies that are distinct from utopia
- instead of a stranger getting a tour of a utopian society, the protagonist is part of the society and has a dawning realization about its nature
- conflict turns on the control of language, and the idea of complicity is central
- dystopia is less stable and more contentous than utopia or anti-utopia
- some dystopias maintain a "horizon of hope" that may be a eutopian impulse

* seven beauties (Istvan Csicsery-Ronay Jr., 2008)
"It is not so much that sf has grown into this position, as the reverse: the world has grown into sf."

science fiction is less often now a form strictly adhered to but a mode of thought that can be termed science fictionality, a mode of reference that frames and tests experiences as if they were works of science fiction
- pushes some to innovate
- some come to embody roles outlined in SF texts
increasingly, hard technology violently interacting with the messy complexities of the human and natural world is becoming our daily life

science fictionality is a state of mind, often experienced as viewing events as if they are happening to us

word he uses ("technoscience") suggests the aesthetics and social outcomes of science more than the actuality

The seven beauties are each an aspect of SF that audiences desire from the genre. They are:
1. fictive neology (new words that indicate a word different from their own)
- neologisms are "knots of estrangement"

2. fictive novums (from Dako Suven, an unpresedented new thing that completely changes the model of reality and thus history)
3. future history (discovery of an alternative history, parallel universe, or concealed past changes the meaning of human history as much as an explicitly futuristic setting. new history must draw on realism, providing details that are naturalistic to connect the reader's present to the new history, making that history the fictional "pre-history")
4. imaginary science (introduces new technoscientific ideas. science in SF is always fabulous, it usually departs or extrapolates on known science in some fantastical way)
5. fictional sublime (SF is the modern genre mostly likely to evoke the responses associated with the sublime...especially since WWII, we have the "technoscientific sublime" a sense of awe and dread in reponse to technological projects that exceed the power of their human creators
6. the science-fictional grotesque (represents the collapse of ontological categories that reason has hereto regarded as distinct, resulting in a spectacle of impossible fusions...domain of monsterous aliens, interstital beings. induces fascination and horror rather than awe. representative of technoscientific phenomena that threaten personal identity)
7. the Technologiade (story that makes sense of contemprary experiences of modernization and ultimately to moralize them by refamiliarization. use myth structures that adapt newness)

SF asks readers to be at once more expansive and more limited than they already are
- science fiction is an oxymoron


gaps of science fiction
- the gap between the conceivablility of future transformations and the actuality of their implementation (how plausible in the conceicable novum?)
- belief in the imminent possibility of transformations and reflection about their ethical, social, or spiritual  consequences (How broad are the potential social conequences that follow from the novum?)

the project of science fiction(ality) is an inherently future-oriented process

unlike historical fiction (of which SF is an heir), SF is in a state of anticipation or suspense because the future depicted is still in the process of coming (or not coming) into reality

SF encroaches on the realm of the transcendant/transcendental, positing that anything in the natural world can, at least potentially, have an artifical analogue (and eventually, therefore, be transformed)

* three faces of utopia (Lyman Tower Sargent)
"in our pride, we commit utopia"
the three faces of utopa seem to be an attempt to achieve utopia (hubris), a failure to achieve utopia (despair), and a rekindling of hope...that is, utopianism, anti-utopianism, and anti-anti utopianism
Sergant appeals to the idiea that there is a utopian impulse—"If we are hungry, we dream of a full stomach"
divides utopianism into communitarianism and utopian literature, and also into urban and rurual utopias
maintains that utopias do not need to be perfect

* Archologies of the Future
Utopia is situated in place and time; in Russia in the 20th century it was associated with Stalinism, for example

what is the state of utopianism in late capitalism/neoliberalism, where there seem to be no viable answer or alternative?

"utopia can only serve to make us aware of our own mental and ideological imprisionment"

Part I: Desire Called Utopian
Part II: Close readings of US sci fi from 20th century

Phillip K. Dick is the "Shakesphere of science fiction"

slogan of "anti-anti-utopianism" provides a working strategy for steering between extremes (communism and anti-communism)

* Forms by Carline Levine
Do forms constrain?
Forms provide affordances, shape how we approach problems and discourses

** Forms about patters
Forms can operate at differnt scales (i.e., genre and syntax)
Forms can persist across periods and cultures, or can be confined to particular places and times
Political structueres can move or be portrayed in a novel, becoming aesthetic forms

** Structuralism
Human discourse orgnaized into universal structures
Uses binary oppisitions (light/dark, male/female) as organizing principles
Binaries are a convenient form

** Affordances
Formalists say: forms matter
Forms shape what can be said and done in particular contexts == affordances
Afforcances comes from design theory
Rymes afford memory, repitton
Networks afford ciruclation
Sonnet highlight single idea or experience
Forms can only do so much, but can be expanded or leveraged in ways that push the form
Forms share one affordance: they're iterative and portable 
No form operates in isolation

** Conflicts between forms
Combinations of forms can be generative, unexpected
Example: biological clock meets tenure clock
Forms overlap--narrative affects poliitcal reality (prisioner can get pardon after new interpretation of crime), political reality affects narrative

** Too capacious?
Are they experiences that arent' forms? (says yes, interstices etc)
Do we spend too much time breaking down forms, ignoring what they actually do and afford?
Scholars look for the formless (hybridity, liminality)
  >> but we need orgnaizing principles, can't get rid of forms ultimately
"one cannot make a poem out of soup or a panopticon out of wool"
a prision is both a thing and a form, created from the affordances of metal and stone while remaining an abstract concept that can be applied across contexts

** Differences (and affordances) between theoretical forms
New Critics forcused on aesthetic form, ignored how it was shaped by political forms
Language of hermaneutics strong for aesthetic forms, weak for the granular assessment of political forms

forms are notentirely outgrowths of partcicularity 
Mark Schneiberg >> "it is preci\sely the endurance of holdover forms that can make a society suprisingly plural"


Both New Formalists and genre theory could benefit from attention to the long sotry of forms, their movement across time and space

forms and genre are not just synonymous (though many they seem so)

genre is commercial and historical, a taxonomy
forms can orgnaize both social and literary objects, are patterns...not really subject to interpretation and debate, since not strictly pegged to a term
>>>form is recognition, genre is labeling?

** What's missing from the Marxist tradition?
Marxists argue that forms blind us to a reality that always exceeds form
Conventional narratives inure people to lives led within exploitative and hierarchical system ("as social subjects")
Marxism assumes that the political (form) is always the root or ground of the aesthetic (form)

Example: Tom Brown's School Days
>>> uses Bildungroman and gender binary forms (aesthetic form meets political form)
both narrative and gender attempt to impose their own shape on the text
"rather than tracking the buried 'content' of the form, I propose here to track the forms of the content"
*** Thesis statement
We don’t know which came first. What we do know is that both the literary and the social form—Bildung and the gender binary—preexist the text in question. Both move from other sites into this text, carrying their own ways of organizing experience with them. While we might speculate about which form is primary, or about Hughes’s own motivations, the text itself shows us something interesting about what happens when narrative form encounters the gender binary and the two begin to operate together. In fact, a predictable, generalizable hypothesis about form unfolds from this collision, regardless of the author’s intentions or the origins of either form. As long as pliability—the susceptibility to development—falls on the feminine side of the gender binary, the Bildungsroman will have to be a feminine genre, even when its protagonists are male.Most Marxist formalist critics would approach the narrative form of Tom Brown’s Schooldays as the working out of an ideological position or as an “abstract of social relationships.”33 Most politically minded new formalists would read the text as a response to the immediate social world around it. The formalism that emerges here is different: I read narrative and gender as two distinct forms, each striving to impose its own order, both traveling from other places to the text in question, and neither automatically prior or dominant. One might say that I am flipping White’s terms upside down: rather than hunting for the buried content of the form, I propose here to track the forms of the content, the many organizing principles that encounter one another inside as well as outside of the literary text. Instead of assuming that social forms are the grounds or causes of literary forms, and instead of imagining that a literary text has a form, this book asks two unfamiliar questions: what does each form afford, and what happens when forms meet?


instread of 

** Not so simple
In theory, politics determines our place
In practice, so many conflicting forms exist (narrative, political, etc) that our environment is necessarily complex

makes the case that no form, no matter how seemingly powerful, dominates all others
"But at the same time I would argue that an exclusive focus on ultimate causality has not necessarily benefited leftist politics. It has distracted us from thinking strategically about how best to deploy multiple forms for political ends."

** Narrative 
Best captures the experience of colliding forms
Present causality as a sequence of events rather than positing an originary cause (i.e., more accepting of diverse forms rather than some dominant cause or superstructure, a "conjoining" rather than a "necessary" connection
Defends her use of paraphrase

** Organizing forms of book
Whole, Rhythm, Hierarchy, Network
*** Will look at:
**** Order imposed by each form
**** How are scholars dependant on organizing forms?
**** Relationship between literary and social forms
**** How new appraoch to multifaced forms would work
* Principles of Hope
If art’s limit were beauty it is simply not enough

likes looking forward, hates looking hackward
Marxism is oriented toward teh future
capitalism worships facts, psychoanalysis deals too much with the past (prefers a kind of unconcsious in potential)
anti-empirical, appeals to art + imagination
interesting: what is the future? does it exist in the present or is it an act of human will or imagination?


People have always dreamed of this,ndreamed of the better life that might be possible. Everybody's life is pervadedby daydreams: one part of this is just stale, even enervating escapism, evenbooty for swindlers, but another part is provocative, is not content just to accept the bad which exists, does not accept renunciation. This other parthas hoping at its core, and is teachable. It can be extricated from theunregulated daydream and from its sly misuse, can be activated undimmed.Nobody has ever lived without daydreams, but it is a question of knowingthem deeper and deeper and in this way keeping them trained unerringly,usefully, on what is right. Let the daydreams grow even fuller, since thismeans they are enriching themselves around the sober glance; not in the sense of clogging, but of becoming clear. Not in the sense of merely contemplative reason which takes things as they are and as they stand, but of participating reason which takes them as they go, and therefore also as they could go better.

this world is a world of repetition  or of the great Time-and-Again; it is a palace of fateful events, as Leibniz called it without breaking out of it. Occurrence becomes history, knowledge re-remembering, celebration the observance of something that has been. This is how all previous philosophers went about it, with their form, idea or substance posited as being finished, even postulating Kant, even dialectical Hegel. In this way physical and metaphysical need spoiled its appetite, in particular its paths

* News from Nowhere (William Morris)
Anarchist utopia
Labor is voluntary
Fear of a work shortage, i.e. work is so pleasureable that people fear they will run short of it
parliment used to store manure
no politics (one-page chapters on "no politics")

* Tenses of Imagination (essays by Raymond Williams) 
Three kinds of science fiction:
Space Anthropology, Utopia, and Putropia
Prefers space anthropology, more uniquely human
Putropia, a breaking down of a utopia

There are four characteristic types of alternative reality, he argues: the 
***  paradise or hell
often reached via a journey, but they journey (space or sea or time) is not important. the type of place is, rather, largely unchanged

paradise and hell only rarely utopian/dystopian

"ordinarily the projections of a magical or religious consciousness" 97

garden of eden is only latently utopian - utopian for Williams seems to imply realizibility

often just played for sensation, may be utopian if more connected to real questions of soceity, but mostly isn't

*** the positively or negatively externally altered world
can often be the result of scientific perspectives, either as explaining prinicples of nature that brought about the change or by a growing understanding of science in a society

"either falls short or goes beyond" utopian and dystopian mode 97

often limits or anuls human achivement, and so tends toward the dystopian
even when utopian, the lack of agency must be taken into considerations (as in Wells' /Day of the Comet/)

*** the willed transformation
"inspired by the scientific spirit" seems to conflate this with the next category a bit. kind of seems like this should be throught of more generally, i.e. utpias based on religion like "left behind." mentions that the scientific spirit can be subordinate to revolutionary or pastoral tendencies, though there seem to be instances of this type that don't really include science
*** the positive or negative technological transformation

brings up Engel's distinction between "utopian" and "scienntific" socialism (the latter is based on a "scientific" analysis of history that makes communism the inevitable product of capitalism)

Bacon's /New Atlantis/ is scientific, More's /Utopian/ is utopian

*** Readings of sci fi

Looking Backward - capatilistic monopoly is next stage of development, oraching rationalism "a work without desire", Williams quotes Morris's critique that Bellamy can't see any alternatives to macinary of status quo and so extrapolates on them
brave new world - "confused" combination of socialism and capitalistic corporatism
dispossed (le guin) - Williams says it's interesting becaus it can explore the utopian and the non-utopian option simultaneously, unlike in /news from nowhere/ or /looking backward/ which use the dream as their "portal". Has "wary acceptance" of  utopain goals and also the realisation that a utopain state can be achived by a few through non-utopian means. I agree with Williams that it's a product of its time (the '70s), made me think of /Woman at the Edge of Time/

*** tenses of utopia (essay)

shows his like for space anthopooogy once again, he's writing about le guin's /dispossesed/

heuristic vs. systematic utopa

heuristic can be too sentimental - /News from Nowhere/ an example of this, also Hyhnamland
systematics can get too into the weeds, can't see ny real life happening there

we do not write alone, writing is a product of synthesis
imagination is not imagination, "it feels like contact"
the process is not distillation or asociation, but formation "you feel your way into", NOT like imagination
 >>> seems to indicate that it's a new thing, but formed of old things

reconstructing the past or the future through this process of formation requires generating a type of "feeling," i.e. a real understanding of the situation (such as infantacide or other unthinkable things) that regards it not only as a foreign or strange thing, but as something that can really be contempated and realiszed

"dispossed" an example of this, not just a systematic look at a new society but a "feeling" exploration of that society

*** passage
In any real future tense, then, what we call imagination seems more like
the usual accounts of it than in either present or past tenses. We speculate,
we project, we attempt to divine, we figure. The actual writing that goes
with that dimension is in its turn distinctive: more general; more imme-
diately accessible to ideas; often more angular and more edged; relatively
low in the kind of saturation by detailed and unlooked-for experiences
so common and ordinarily so valued in the other tenses. I do not want
to turn a contrast of kinds into some order of merit. Each kind of writing
does quite different work. But if that is a recognizable kind of imagina-
tion – over a range from the secular and political to the solidly traditional
and the surprisingly private visions and divinations – there is a problem in
using not just the same word but the same concept, pointing to the same
general process, in the other tenses. The problem is already there, however,
in the everyday range of the word. The mental concept of something not
present to the senses, which corresponds to future-writing and to many
kinds of fantasy, coexists in the language with the sense of empathy, of feel-
ing our way into a situation which in a general way we know but which we
can come to know as it were from the inside – a sense which I think is not
far from the idea of discovering and being moved by a structure of feel-
ing within what is already nominally and even carefully known. Yet if the
word can be applied to either process, the real processes are still different,
and the key difference, as it matters in writing, seems to me essentially a
matter of real tense. (123)

* To read
Wells /Day of the Comet/
/The Coming Race/
demand the impossible

* commonplace

** tenses of imagination

But now, very clearly, there are other deeper forces at work, which perhaps only imagination, in its full processes, can touch and reach and recognize and embody. If we see this, we usually still hesitate between tenses: between knowing in new ways the structures of feeling that have directed and now hold us, and finding in new ways the shape of an alternative, a future, that can be genuinely imagined and hope- fully lived. There are many other kinds of writing in society, but these now – of past and present and future – are close and urgent, challenging many of us to try both to understand and to attempt them.
* scraps of the untainted sky
"And so it is that sf finds ways to explore and to go where others will not, might not, dare not go. It's not the only creative mode to do so, but it is one that has evolved and acquired a relatively privileged niche in the cultures of modernity"

"a good deal of sf-especially since the early 1980s-suffers from a standardization and simplification imposed by the constricted financial demands of publishersand distributors, the texts that do draw on the full measure of the formal capacities of the genre and rise above prevailing common sense and market mediocrity"

"text as mere fantasy, and therefore meaningless. Put simply, they don't get sf because they don't realize the consequences, formally and logically, of the text's particular mechanics-namely, its ability to generate cognitively substantial yet estranged alternative worlds.6"

"As many writers, fans, and scholars of sf have noted, the experienced sf reader moves through a text like a traveler in a foreign culture or a detective seeking clues to unravel the mystery at hand.'0 Both proceed incrementally, observing and gradually absorbing information, making patterns, discovering ways to see and understand the larger picture in its own right, and finally to act decisively within that"

"consciousness-raising discoveries of feminists and their male allies, or the theorypractice analytical spiral of a noncompromised socialist opposition.8

"The specific textual strategies of sf and the resulting feedback loops in the reading practices learned by what Edward James calls the "determined reader of sf" are my initial topics when I teach sf.9 Although there are undeniably as many ways to read the sf text as there are actual readers, those who are familiar with the fictive maneuvers of sf (whose skills are sometimes enhanced by their participation"

* follow up on these
Johanna Russ has said the SF is a "didactic literature"
look at "When It Changed" by Johanna Russ
typtree's /Houston Houston/  about men/women

* speech
"On this view, the future has already arrived, and its name is the present." from review of jameson [[http://www.lrb.co.uk/v28/n05/terry-eagleton/making-a-break][here]]
Are we in the "Age of Alienation" (Brecht, Suven) we are in the midst of futurist anxieties
utopian lit seems obsessed with definitions and taxonomies
Sergant appeals to the idiea that there is a utopian impulse—"If we are hungry, we dream of a full stomach"

estrangement/distance a condition of our modern lives
- extensive use of media encourages us to see ourselves in the third person
- this is why we feel that we are in a social future

* questions
** What is the role of new language (fictive neologism) in utopian works?
serves as a break, a novum that allows for distance and estrangement
according to moylan and baccelini, language is used in dystopia to suggest complicity...escape is only provided by learning other language (1984, anthem, the giver)
real life utopian language projects: esperanto, loglin
a deepness in the sky, the linguist gives up her humanity to communicate with aliens

** what is the state of utopianism in late capitalism/neoliberalism, where there seem to be no viable answer or alternative?
- crusing utopia draws on ernst's bloch's principles of hope, puts forth queerness as a source of hope that should exist perpetually on the horizon
- transhumanism/open source humanity, like in accelerando
- 

** Why have utopias florished in one era and dried up in another?
- actual question for carrie, this is a tough nut

** How can works that posit the end of history offer any useful historical impulses?
how can visions of the "epoch of rest" (Phillip Morris) stir us to action?
there' a dialectic between how close a work of art is to its society of origin...if too close it has no impact but too far and it becomes ridiculous and irrelevant

** why is the genre of fantasy not fully utopian?
fantasy looks at the ontology of the past, science fiction looks at the ontology of a chosen future




* concepts
Cognitive estrangement (Darko Suvin) - sci fi that uses cognitive estrangement presents a "novum", or something that is completely new, that forces the reader to confront a completely different worldview (related to Brect's alienation/verfremdung effect, presented in Suvin's Metamorphases of Science Fiction)

 realitis and possibilities that contradict the status quo

anti-relationality - in the book /No Future/, Lee Edelman says that the child is the central figure in western political tradition...queerness can reject the figure of the child and thus poses a credible threat to western patriarchy
- this could be interesting if related to futurism and the singularity...new discourses center on A.I., which is a new version of the child. in that reading, the figure of the A.I. or the posthuman makes humanitiy itself a form of queerness. could use /Accelerando/ and /Saturn's Children/ to talk about this. also silicon valley's youth obsession could be part of this. (orig) 

amusing article on queer theory: http://www.critical-theory.com/what-the-fuck-is-queer-theory/
imminent worldview (Empire, Negri and Hardt) - one that denies the existance of transcendence

value pluralism - the idea that there are fundamental rights that might be equally correct yet still in conflict with one another



* test
** history of utopian thought
stuff about prophets vs apocalyptists, prefers prophets (is marx a prophet or apocalyptist?)

** scraps
move through sf like a foreign land
** empire 
biopower/biopolitics
internation conflict to making enemy a criminal
empire rules over human nature
** red planet
bossing (negative space)
20,000 leegues and matrix (reads in terms of negative space not on their own terms)
reaction to suven
** crusing utopia
aligned with bloch against elelman
anti-anti-relationality, thinks anit-relationality comes from its own kind of privelage
examples from chelea girl, andy warhol
queerness should be a potentiality, not assimilationist
** dark horizons
about dystopia
distinguishes b dystopia and anti-utopia
dystopias based on instability of language
** seven beauties
science fictionality (world in which people read their lives as science fiction)
fictive neology
technoscience
technoscientific sublime
neologisms are "knots of estrangement"
** three faces of utopia (sargent)
utopias don't need to be perfect
"in our pride, we commit utopia"
utopian hype cycle (hubris, nemesis, hope)
** archeologies of the future
wants a third option, not modernity (marxism) or postmodernity (neoliberalism) but a third option
anti-anti-utopianism, steers us between extremes
** spaces of hope (david harvey)
made me actually think about marxism again
we now think that we are post-marx, but we shouldn't be
focuses on the idea that capital breaks through boundaries it establishes for itself

** marx
terry eagleton says that marx is more concerned wiht the indicative than the subjuntive
** metamorphases of science fiction (suven)
science fiction should frame a hypothesis, some works that don't do this aren't at their core science fiction (star wars)
cognitive estrangement - rather than a hypothesis or small change, some works present a full alternative to our reality which allows for subversion and the ability to imagine other ways of living
** tenses of imagination (andrew milner)
interested in the "structure of feeling" that sf engenders
space anthropollogy
petropia
doomsday
sf goes where other texts will not go
sf = "cognitively substantial yet estranged worlds"
sf reader is a detective seeking clues, a foreign traveller
four types of dystopia
hell - wreched life
externally altered world - new life brought about by uncontrollabale natural event
willed transformation - new an unhappier life brought about by new social order
technological transformation
