
* Forms by Carline Levine
Do forms constrain?
Forms provide affordances, shape how we approach problems and discourses

** Forms about patters
Forms can operate at differnt scales (i.e., genre and syntax)
Forms can persist across periods and cultures, or can be confined to particular places and times
Political structueres can move or be portrayed in a novel, becoming aesthetic forms

** Structuralism
Human discourse orgnaized into universal structures
Uses binary oppisitions (light/dark, male/female) as organizing principles
Binaries are a convenient form

** Affordances
Formalists say: forms matter
Forms shape what can be said and done in particular contexts == affordances
Afforcances comes from design theory
Rymes afford memory, repitton
Networks afford ciruclation
Sonnet highlight single idea or experience
Forms can only do so much, but can be expanded or leveraged in ways that push the form
Forms share one affordance: they're iterative and portable 
No form operates in isolation

** Conflicts between forms
Combinations of forms can be generative, unexpected
Example: biological clock meets tenure clock
Forms overlap--narrative affects poliitcal reality (prisioner can get pardon after new interpretation of crime), political reality affects narrative

** Too capacious?
Are they experiences that arent' forms? (says yes, interstices etc)
Do we spend too much time breaking down forms, ignoring what they actually do and afford?
Scholars look for the formless (hybridity, liminality)
  >> but we need orgnaizing principles, can't get rid of forms ultimately
"one cannot make a poem out of soup or a panopticon out of wool"
a prision is both a thing and a form, created from the affordances of metal and stone while remaining an abstract concept that can be applied across contexts

** Differences (and affordances) between theoretical forms
New Critics forcused on aesthetic form, ignored how it was shaped by political forms
Language of hermaneutics strong for aesthetic forms, weak for the granular assessment of political forms

forms are notentirely outgrowths of partcicularity 
Mark Schneiberg >> "it is preci\sely the endurance of holdover forms that can make a society suprisingly plural"


Both New Formalists and genre theory could benefit from attention to the long sotry of forms, their movement across time and space

forms and genre are not just synonymous (though many they seem so)

genre is commercial and historical, a taxonomy
forms can orgnaize both social and literary objects, are patterns...not really subject to interpretation and debate, since not strictly pegged to a term
>>>form is recognition, genre is labeling?

** What's missing from the Marxist tradition?
Marxists argue that forms blind us to a reality that always exceeds form
Conventional narratives inure people to lives led within exploitative and hierarchical system ("as social subjects")
Marxism assumes that the political (form) is always the root or ground of the aesthetic (form)

Example: Tom Brown's School Days
>>> uses Bildungroman and gender binary forms (aesthetic form meets political form)
both narrative and gender attempt to impose their own shape on the text
"rather than tracking the buried 'content' of the form, I propose here to track the forms of the content"
*** Thesis statement
We don’t know which came first. What we do know is that both the literary and the social form—Bildung and the gender binary—preexist the text in question. Both move from other sites into this text, carrying their own ways of organizing experience with them. While we might speculate about which form is primary, or about Hughes’s own motivations, the text itself shows us something interesting about what happens when narrative form encounters the gender binary and the two begin to operate together. In fact, a predictable, generalizable hypothesis about form unfolds from this collision, regardless of the author’s intentions or the origins of either form. As long as pliability—the susceptibility to development—falls on the feminine side of the gender binary, the Bildungsroman will have to be a feminine genre, even when its protagonists are male.Most Marxist formalist critics would approach the narrative form of Tom Brown’s Schooldays as the working out of an ideological position or as an “abstract of social relationships.”33 Most politically minded new formalists would read the text as a response to the immediate social world around it. The formalism that emerges here is different: I read narrative and gender as two distinct forms, each striving to impose its own order, both traveling from other places to the text in question, and neither automatically prior or dominant. One might say that I am flipping White’s terms upside down: rather than hunting for the buried content of the form, I propose here to track the forms of the content, the many organizing principles that encounter one another inside as well as outside of the literary text. Instead of assuming that social forms are the grounds or causes of literary forms, and instead of imagining that a literary text has a form, this book asks two unfamiliar questions: what does each form afford, and what happens when forms meet?


instread of 

** Not so simple
In theory, politics determines our place
In practice, so many conflicting forms exist (narrative, political, etc) that our environment is necessarily complex

makes the case that no form, no matter how seemingly powerful, dominates all others
"But at the same time I would argue that an exclusive focus on ultimate causality has not necessarily benefited leftist politics. It has distracted us from thinking strategically about how best to deploy multiple forms for political ends."

** Narrative 
Best captures the experience of colliding forms
Present causality as a sequence of events rather than positing an originary cause (i.e., more accepting of diverse forms rather than some dominant cause or superstructure, a "conjoining" rather than a "necessary" connection
Defends her use of paraphrase

** Organizing forms of book
Whole, Rhythm, Hierarchy, Network
*** Will look at:
**** Order imposed by each form
**** How are scholars dependant on organizing forms?
**** Relationship between literary and social forms
**** How new appraoch to multifaced forms would work



