* Deadly Encounters
1861: "sensation was the sensation"
- a craze that lasted a decade
- murders in the summer of 1861 started craze for sensation

poisonings, family of six and lover with arsenic-laced hot chocolate
Constance Kent, murderer in the case from The Suspicions of Mr. Witcher
French acrobat, worked at Crystal Palace, did feats such as cooking himself an omlet on the tightrope
warehouse fire burned a quarter mile of waterfront property

Murray: Northumberland Street Affair
- "murderous encounter in Nothumberland Street"
- also called "frightful encounter" and "deadly encounter" and "desperate affray"
- after meeting a man calling himself Gray in the street, Murray, a military man, was brought to his office here he was shot
- Gray (later identified as Roberts) thinks Murray is dead, giving Murray the oppurtunity to attack him with a set of tongs
- bloody melee ensues, leaving the office covered in blood (later sensationally described in the papers, saying the blood was like a rainstorm)
- readers were allowed to "sup full of horrors" as the newspapers described the incident and the scene in dramatic and extensive detail
- suspicion was that there was a "woman at the bottom" of the incident

- could Murray have shot himself? "it would appear to have been a mode of self-destruction available only to a despondent contortionist"
- extensive descriptions of Mrs. Murray, who had been meeting with Roberts before the incident: "an air of calculation in her dress and demeanor"
- according to Mrs. Murray, Roberts had lent her money and implied that she wouldn't have to pay it back if she did the obvious--she turned that down but couldn't pay anything but the interest

* The Beetle
Robert Holt is susceptible because he is down on his luck, if he had been wearing proper clothes he would have been more resistant to mesmerism

It was as if some strong magnetic current had been switched on to me through the window to draw me into the room.



 'Pray, sir, are you a magician?'
He replied to my question with another.
'You, Mr Atherton,--are you also a magician?'

* Victorian Science in contexxt (Lightman, 1997)
this book is contextualist, which moves away from sweeping intellectual history to ask about local power relations. "Who's truth?" is the main question here. 

the book examines victorian science and comes away with an impression of victorian culture

argues that science doesn't stand apart, needs to be considered in the context of victorian culutre, both to understand victorian science and to understand victorian culture

observes a distinction between an old guard of Tory/Anglican scientists who were upper class and more religious and that controlled Oxbridge and the societies (Charles Lyell, Adam Sedgwick, William Whewell, andJohn Herschel)) and a set of middle class scientists that were more secular (Huxley, Spencer, Tyndall, William Clifford, Lewes, Edward Tylor, John Lubbock, Edwin Lankester, Edward Clodd, and Henry Maudsley)
- new group put forth more naturalistic (in the sense of immenance, or presence in the world)

telaks about the externalism/internalism debate in the history of science in the 1960s
- the Hessen theory (externalist) was that Newton's /Principia/ was created to cater to the goals if 17th century industry and economy, and that Newton was inspired by his economic status and context. Hessen's theory may itself have been influenced by internal Soviet politics, he was obliquely defending Einstein
- science, technology, and war are linked
- internalism focuses on the rational reconstuction of scientific ideas and the development of scientific ideas within the scientific world

science central to victorian culture
- ceremonial, funerals of Kelvin and Darwin
- spectacular, Crystal Palace exhibition
- sensational, /Vestiges of Creation/

victorian science colored literature
- hardy's /Jude the Obscure/ was Darwinian
- Eliot was an amateur naturalist, Lydgate in /Middlemarch/ a scientific character
- Tennyson's /Memorium/ explores religious doubts
- /Hard Times/ explores narrowness of utilitarian perspective
- Butler campaigned against Darwinian theory but also wrote books on evoution (from a Lamarkian perspective)
- Ruskin head of geological society

gentlemen of science were in a unique position to reinterpret sources of social order

** Chapter: Satire and Science in Victorian Culture by James Paradis
** Part I: Defining knowledge
intro talks about Carlyle /Sartor Ressartus/, which is at once a parody of science and an unstable grasping at truth
- carlyle uses the aesthetics of science to explore a word in which science is irrelevant
- "in accouting for everything, science ends in accouting for nothing"

Victorian scientists had to demarcate true science from false science

** Orthodoxy and Unorthodoy (Alison Winters)
becoming harder to lump old-school Oxbridge gentlemen scientists together, their positions and science itself in the 19th century were underdetermined and multivalent

uses the term heterodox science instead of derogatory pseudoscience
"retrospectively regard as heterodox or marginal cannot be considered
unambiguously to have held that status at a time when no clear orthodoxy existed that could confer that status upon them." (winters 26)
- some scientists focused on immanence, some on transcendance
- could also choose beteeen a monistic view of the world (spirit and matter unified)

** Part II: Ordering Nature
Society has scientists read into nature a variety of messages charged with ideological significance
** Part III: Practising Science
How did mechanisms and conventions of science influence the dieas of victoain scientists?

literature became a way for victorian scientists to disseminate their ideas (water babies, etc), often quite reductively. Satire could resist scientific reductionism here

* darwin's plots (Gillian Beer)
the human, everywhere and nowhere in his argument
reference's Dawkin's memes

Darwin's Dangerous Idea (book): the algorithmi
c level is the level that best accounts for the ... shape of the wing of the eagle
- cats can be said to make mice

Darwin produces different narratives
- sociobiology, genetic determinism
- proliferation of genes can produce diverse outcomes
- cloning is the contrary of evolution

Darwin's plots are
- garden, growing
- plans, mechanations

darwin's non-technical language allowed his ideas to be adopted

the origin "included more than its maker knew, despite all he did know"


darwin wanted to know if hybridism produces sterility

see darwin as less assured and more deflected by insight than major biographies
- feels that darwin is less a stereotypical product of his time, has empathy for other forms of life and assays ideas contrary to his time

points out cuthington, darwin's servant, who is not mentioned on any page of the book

taxonomies always cause trouble with boundaries
- they draw on prior assumptions
- "their values tend to form an evidential circle about what matters for categorization"

darwin questions the categorizing zeal of human beings
- my note: interesting in light of Gould's criticisms about the overzealousness of those looking to use adaptation as an explanation for all traits (Spandrels of San Marco)

major theories tax, aff
- distrub assumed relationships
- shift what is substantial into metaphor ("earth now only seems immovable")

in 1850s and 1860s, evolution was called the "development hypothesis"



"if" theory > description > cosmology > quotidian techniques and procedures

reading the Origin involves you in a narrative experience, subjective and literary

we live in a post-freudian age, his ideas are institutionalized
- the years after darwin were a post-darwinian age, his ideas seeped into the culture to the point that it didn't matter if someone had read his book or not (almost)

in our own day scientific ideas tend to reach us through translation and extrapoloation
- we use the term "layman" unironically to talk about non-scientists

darwin's theories are fundamentally multivalent, they aren't just read one way (ascent/descent, immortality/death, etc)

herschell: characterizes darwin's theory as "the law of higgldy-piggeldy"

one of the trends in reading Darwin is to try to put man back in the center of it, recasting darwin's theories to single out man

origin of species = work of biology
desacent of man = work of anthropology

* time lord
sir sanford fleming - Scottish transplant to Canada
- developed standard time


North American trains had bogies, which reduced shocks and allowed the train to go around turns without knocking everyone over
- north american trains more democratic, cars arranged with a stove in the middle and people can walk freely
- american railroads were cheaper due to the low cost of land
- america the home of luxury in transit, britain the home of speed

contends that culture, like newtonian objects, has inertia and persists until it is deflected
- uses example of china, claiming that the chinese court had a time monopoly

the ultimate time theft is slavery
- in jazz, time is a dialectic

democratic time
- wages, contracts, and patents
- rents, interest, and schedules
- recognition of impermenance of many civil institutions

not only rails, but also weather, requires standard time
regimes based on containment, like ottomans, were put in jeopardy by the new time and the new mobility

time was based on the solar noon
- but each 1100 feet is a differnt solar second

fleming found the expression local time to be objectionable
- there is no such thing, there is only one time
- guess he wasn't thinking about relativity

thoreau had anxiety about new machine time
- "we do not ride upon the railroad, it rides upon us"
- machine men have no leisure for integrity

dombey and son has a lot to say about time and the railroad

3000 miles, a six-month journey, could be covered in five days in a comfortable railroad car


** look into
thomas huxley
descent of man
vestiges of the natural history of creation
* Dracula
"my metaphor be more dishonour to science than wolves be of danger to man."

Mina's hypnotic messages from the Count like telegraphy

"I took the papers from the safe where they had been ever since our return so long ago. We were struck with the fact, that in all the mass of material of which the record is composed, there is hardly one authentic document; nothing but a mass of typewriting, except the later note-books of Mina and Seward and myself, and Van Helsing’s memorandum. We could hardly ask any one, even did we wish to, to accept these as proofs of so wild a story. "

* victorian scientists
** The X-Club (new scientists that came up in the 1870s), promoted ideological neutrality (for their own ends, accouding to Vic Science in Context)
*** Huxley
*** Tindall

*** Wallace
Attacked ideological neutrality. Wrote /Human Selection/ and /Human Progress/. For him, social progressionism and biological progressionism went hand-in-hand. Advocated for socialism and feminism.


* questions
What does objectivity mean in a scientific context? How does change in scientific theories occur?
boundaries in science? between science and politics, science and religion, science and pseudoscience, ex- pert and nonexpert, orthodox and unorthodox, the material and the tran- scendent, the material and the psychological.


* look into
The Politics of Evolution (1989), a his- tory of science "from below," by Desmond
- contrast with "Gentlemen of Science"

Sartor Resartus (1831) by Carlyle, introduces itself as a scientific study of clothes, considered that Victorian science is almost a victim of its own success because everything has been studied, critiques science as a parody



* pseudoscience
carlyle, sartor rassartis
alison winters, true and not true science
