* discussion points

** nature of knolwedge
novum organum - Bacon lays down the fundamentals of the scientific method. emphasis on empiricism and on creating reliable facts and knowledge that can be iterated upson, and (importantly) that have ALL been confirmed with observations and/or experiments

resolutive compositive method - the system used by Hobbes in works like Leviathan. Consists of looking at a phenomenon and dialectically breaking it down into its constituant parts (resolving it), then composing it back together in an attempt to better understand it. For example, in his discourse on names, Hobbes divides names into proper names and common names, then he reflects that common names have a property of the universal. He then breaks down the idea of the universal, saying that without the power of names a person cannot form abstraction, such as knowing that what's true about one triangle is true of other trianbles. (The name "trianble" or similar is needed.) Thus he concludes something about names and language, that they allow us to perform abstraction.
- /Leviathan and the Air Pump/ (SHaefer and Shapin) attempts to resurface Hobbes' approach to knowledge, suggesting that it's not correct stick the "self-evident" mode in the history of science

Humboldtian science - the science that looks at a diverse array of phenomena to find some underlying universal cause. This difference from Baconian science was suggested by Susan Cannon (he/him/his)

Mill's /System of Logic/ - Describes methods for creating new knowledge based on gathered facts, or the art of logic. Suggests that there is an inherent ability in humankind to draw conclusions, but that this faculty can be developed with the methods presented.

Law of Correlation -  Advanced by Cuvier. the conception that, based on a point of evidence, one can reconstruct the whole phenomenon or system. "Show me the bone, and I will describe the animal." Holmes's /Book of Life/: "From a drop of water, a logician could infer a Niagra"

Problem of induction - Hume suggested that our beliefs that trends will continue (a form of induction) is not rational, but is still necessary. Karl Popper (/Conjectures and Refutations/) notes that using induction (i.e., going from evidence to theory) is impossible since theories can never be proven (black swan). Instead, you should attempt to work the other way, trying to deduce problems in your theory (looking for evidence that contradicts it). If you look for a long time and find nothing, you have a solid (though not proven) theory.

types of knowledge in Victorian fiction:
- Dracula: based on the Humboldian method, they nee a unifying theory of vampirism in order to take down the count. this includes his need for grave soil, which can then be traced by meticulous notes by Mina, and the "Vampiric telegraph," which is derived largely from studying Renfield and then applied to Mina to track the Count
- Hound of the Baskervilles: Holmes draws on the Law of Correlation. His entire method is based on Cuvier's system ("show me the bone and I'll describe the animal" as paraphrased by Mitchell), he observes a component of a phenomenon or system and can reproduce the entire phenomenon. 



The Victorian open mind is a consistent tendency in late 19th-century literature based on an internalization of this problem of induction that leads Victorians to embrace heterodox science (pseudoscience). Possibly a result of the disorientation Schivelbusch points out is the prodcut of new developments in technology (transport and communication in particular)

open mind examples:
- water babies: deal in what you see, not what you do not see. "cannot" is a rash word
- Dracula's Van Helsing: "that faculty which enables us to believe things which we know to be untrue.' For one, I follow that man. He meant that we shall have an open mind, and not let a little bit of truth check the rush of a big truth, like a small rock does a railway truck." he has an "absolutely open mind" and is a philosopher, metaphsician, and advanced scientist
- The Beetle - Sydney Atherton's knowledge of mesmerism is given as a matter of course. Champnell, a man of the world, has already been exposed to an experience with the cult
- a characteristic of Holmes is his skepticism, he does not have the Victorian open mind. this could be a reason for Doyle killing him off at Reichenbach Falls (the new science of vitalism) and replacing him with figures such as Professor Challenger, based on the archetype of the open mind. Huxley, who Holmes was supposedly based on, actaully directly challenged Cuvier's approach with an inductive argument, giving evidence (pig's feet) that showed that reconstruction is impossible
- according to google ngrams, the term "open mind" originated in the 19th century and became much more prevelant toward the end of the century. first recorded use is Carlyle in the 1820s


if there is a choice in Dracula for women between vampirism and the typerwriter (Kitler), then in The Beetle it's the telegraph and the train

** race and type
Brantlinger's /Rule of Darkness/ resists the naive idea that the early 19th century was not about empire because of the lack of discourse about race and the lack of explicit jingoism until after the uprisings in india and ireland
- suggests race is a weakness of Marxist analyses of imperialism

Murphey (/In Science's Shadow/) contends that science was used to marginalize women

** relationship between literature and science
Gillaen Beer (Darwin's Plots) shows how Darwin's rhetoric, his literary side, is largely responsible for his success

Anne DeWitt (/Moral Authority/) places a dividing line in the late 19th century when scientists become professionalized. before, they were "men of science," after, they are "scientists." before professionalization, science is well-integrated into novels. she uses the examples of Gaskell and Eliot (I would use Goethe) as novels before professionalization where science is well-integrated and part of the moral landscape. after professinalization, there is a perceived break between science and literature, she considers Wells /Time Machine/ to be representative of the break between science and the wider culture. she doesn't consider /Frankenstein/ or things like /Der Sandmann/ to contradict this trend, since she claims that those novels arent' fully concerned with science, science in those novels is often a stand-in for the concerns of the artist etc. I would point to novels like /Gulliver's Travels/ to show that there was a preexisting trope that science led to moral failing.

Levine weighs in (/Darwin and the Novelists/) in exploring how intermingled science and literature are in the period. big example is /Little Dorrit/ (and actually Trollope). /Little Dorrit/ is a confluence of three Victorian paradigms: evolution, second law of thermodynamics, and natural theology. Not sure this did anything that Beer didn't do better in /Darwin's Plots/



  
* A System of Logic (John Stuart Mill)
logic is the science of reason, and also an art founded on that science

logic as commonly used goes well beyond working with syllogisms or reasoning from the general to particulars. it also reflects a command of premises, that the logician's knowledge is under their command for argumentative use

"the science which treats of the operations of the human understanding of the pursuit of truth"

logic is the guidance of one's own truths
rhetoric is concerned with conveying those truths to others

some truths are known directly (bodily sensations, intuition). some come to us through the mediation of other truths
- there is no logic for the fact that we see what we see and we feel what we feel
- tricks of perspective show that our senses, which true of themselves in a sense, are not necessarily accurate reflections of the world

questions of what is directly apprehended and what is inferred based on other truths are a question of metaphysics

logic must be confined to questions about conclusions based on truths previously known, not about intuitive or direct truths
- logic is not the science of belief, but the science of proof based on evidence

"logic doesn't find evidience, but determines whether it is found"
- logic doesn't give proofs, but tells you want makes proofs

logic is /ars artium/, the science of science

logic is concerned not with data, but with the relations between data that need to exist to produce conclusions

mankind judged of evidence before logic was a science, and created great mechanical works before understanding the laws of mechanics
- however, there are limits to what mechanics can do without the laws of mechanics, and also what thinkers can do without laws of logic

logic includes the operation of naming, since language is an instrument of thought
- this is interesting in light of J. L. Austin's /How to Do Things with Words/, which takes as its method the decomposition of common words and phrases to get at the underlying principles of our thought

what the art of logic doesn't need for its practical ends, it leaves to metaphysics

logic has no interest in ulterior (that is, metaphyiscal) analysis

nothing in the book is useful for application to areas of knowledge or speculation that are yet undecided. (basically, unless you can agree on some set of facts, you can't use the principles here)


names, according to Hobbes, are sounds we assign to some thought we have that, when used, can inspire that thought in others

Five Methods
- Direct method of agreement: If two or more phenomena have a circumstance in common, the circumstance is either the cause or the effect of the phenomenon
- Joint method of agreement or difference (application of the above)
- Method of residue: If, after removing the causes and effect relationships that are known to apply in a situation, there is a cause and an effect left, the remaining cause can be assumed to relate the the effect
- Method of concomitant variations: If some circumstance is known to vary in relative proprtion to some other circumstance, then the one circumstance is the cause or effect of the other. (i.e., if there levels of toxicity of water increase concomitatnt to lead, then the presence of lead can be known to be the cause)

* Darwin and the Novelists (Levine)
science tries to explain reality, the novel tries to depict it, this book focuses on the mingling of these methods
- tries to show science nad art fusing

Little Dorrit embodies the tension between three forces in Victorian science: natural theology, evolution and degredation (the second law of thermodynamics)
- most religious of Dicken's novel
- explored unreddmed nature of society
- breakdown of the self

levine talks about Mansfield park

* Moral Authority: Men of Science and the Victorian Novel (Anne DeWitt)* 
Lyle believed that science  was morally beneficial, that it should be the cornerstone of a liberal education

Lyle was attempting to professionalize the study of nature

the novel became a locus of examining whether this interaction with science and morality was successful

before professionalization, science was integrated into the novel. after professionalization, science was considered to be something apart and more morally suspect

the science of Darwin (pre-professionalization) shared a common language with a wider Victorian public, which was part of Darwin's success
- common language allowed ideas to move rapidly between science and literature

in the Victorian period, science and literature were intellectual projects in common, scientists using literary methaphors and quotations and writers using scientific ideas

two narratives: moral excellence leading to scientific prowess, and science leading to moral excellence. /moral authority/ primarily concerned wth the latter (science leading to morality)

Barton observes that the promient term for Victorian scientists were "man of science" rather than "scientist," which connoted narrow professionalism

H. G. Wells felt that science led to moral narrowness

the female gothic is central to tales of moral failure in science. the female trespasses into a domain that she should not and is punished for it (frankenstein)

isn't really concerned with the contradition that novels such as Frankenstien and The Sandman propose, since these gothic novels are often not concerned with science /qua/ science
- i would disagree. there are other novels like Gulliver's Travels that show that there is a trope that science leads to moral imbecility

* "Sherlock Holmes, Order, and the Late Victorian Mind" (Christopher Clausen)
the Holmes canon covers so much ground that it offers insight into evolving attitudes

beginning: "I am a brain, watson...all the rest of me is a mere appendix"

the holmes stories are published over such a long period of time that they can show shifting victorian attitudes

Holmes reflects a Victorian terror of the domestic crime: "the butler did it" was a present fear based on class conflict
- Holmes is the guardian of a threatened society

World War I put an end to the feeling that cool reason could prevail
- attributes the decline in quality of the post-1914 tales to this

* Evolution: The History of an Idea (Peter Bowler)
Darwin was original, there wasn't just "evolution in the air"

difficult to see Darwin's originality since many of his revolutionary ideas now seem obvious

Lamark's 1809 theory (soft evolution, the tendency toward greater complexity, spontaneous generation) had been widely rejected

by the 1850s, some naturalists, like Herbert Spenser, were approaching an idea of a natural progression over time (and of course Wallace famously articulated evolution around this time)

Darwin's original insights:
- work of the animal breeders throws light on natural selection
- went against the teleological view (the word itself, evolution, refers to the unrolling of a scroll, suggesting inevitability)
- the undirectedness of indiviaul varients in a population seemed to go against the process being directed by a benevolent creator
- species are no longer to be considered idealized types, but rather individuals subject to variation
- tree of life very radical. was radical taxonomically (implications for how species are formed into groups)
- the struggle for existance (no benevolant god?)

the tree was revoltuionary. contempoary theores included:
- Sharp Macleay's quinary or circular system in which each genus has exactly 5 species (???)
- /Vestiges/ (Chambers) has an orderly system in which species advance along predetermined parallel lines within each family
- these only make sens eif you imagine nature as the product of a divine plan

Darwin picked up "biogeographical insights" on the Beagule voyage. the Galpagos was almost like a perfect experiment in forking descent based on geographic barriers

Adrian Desmond and James Moore proposed that Darwin moved toward evolution and a common ancestor because he hated slavery
- all races come from common ancestor

* The Water Babies (Charles Kingsley)

takes the victorian view of the (scientific) open mind as one that accepts the impossible (fairies)

articulates the problem of induction pretty wellL:
"a water baby? you never heard of a water baby? perhaps not. ... There are a great many things in the world that you never heard of, and a great many more which nobobdy ever heard of, and many things, too, which nobobdy will ever hear of ... But there are no such things as water babies. How do you know that?"
- the water baby is like the black swan

even the wisest men (Owen, Darwin, Huxley) would not say that something could not exist
- only hucksters say "that cannot exist"

cannot is a rash word

there are dozens of things that would be contrary to nature, if we did not see them going on before our eyes all day long

suppose you describe an elephant in detail. you wouldn't be believed. "your elephant is contrary to nature" 
- people would react as a pacific islander to the prospect of snow and ice

wise men examine what is, and not what is not

if a water animal can change into a land animal (amphibian, dragon fly), why cannot a land animal change into a water animal?

the argument about the plausability of the water babies suggests that the outlandishness of nature implies that there are possibilites and unseen marvels  undiscovered

"degredation is impossible" makes evolutionary biological argument for "degredation" or reverse evolution, and also questions whether degredation is really degredation

when the lord see Tom's "husK," not being a member of the Linean Soceity he assumes he is dead (satirical)

professor doesn't change his theory based on evidence

* Leviathan and the Air Pump (Shapin and Schaffer)
about the debate that took place around the invention of the air pump that questioned the validity of scientific experiment

Shapin and Shaffer push back against the "self-evident" mode in historical and cultural discourse in which ideas from the present day are unselfreflectively imposed on the past. the idea at stake here is the epistimological validity of empiricism as a source of knowledge
- breaking out of our cultural framework is a fraught process and can often result in expulsion from a community. therefore we need to play the stranger, not be the stranger. "calculated and inform

Hobbes did not use empiricism, but the "resolutive compositive" method

Hobbes uses a resolutive-compositive method of creating knowledge rather than an empirical

* Knowledge in Transit (Secord)
rather than science in context, knolwedge in transit

narrative frameworks in history of science need to come to terms with diversity
- the centrality of processes of movement and transmission are important to ethnography and the history of reading

wants to resist the sobilization of science (Sobel wrote /The Longitude/, which is subtitled /the story of a lone genius who .../

says the most common mode now in the history of science is to find a theory or invention and localize it's production
- the ur-text here is Shapin and Schaffer's /Leviathan and the Air Pump/

resists "unconceptualized boundaries," arbitrary distinctions between, say, victorian and modernist writing

resists the rise of narrative in the history of science, including science in context (lightman) and /Leviathan and the Air Pump/ (Schaffer and Shapin)

"science is situated knowledge" Donna Haraway

imiplies tthat putting an idea or a piece of science in its context is not in itself a productive work
- the lesson this teaches is that knowledge is ineluctably local
- this localizing can lead to parochial antequarianism

the more local science becomes, the more difficult it becomes to see how it travels

takes from reader response in wishing to analyze the communities of reception that read, for example, Faraday. we know a lot about his lectures and his influence on the royal society, not much on his impact on the wider society
- how were his publications made available in other countries
- we have no sense about how his reputation was actually developed

the narrative mode draws us toward teleology

likes Bruno Latur and actor network theory, but thinks his model is too abstract for historians
- hard to give equal agency to humans and nonhumans
- at least makes nonhuman networks more open to historical analysis

* Show Me the Bone (Gowan Dawson)
book traces the law of correlations across the long 19th century, from the early 1800s to the first world war

could relate Cuvier's feats of identification to Holmes's feats of induction

there is a two-way communication between science and the general public
similarly, the relationship between science and literature is two-way

Mitchell, in his own fantastic claims, paraphrased Cuvier as saying "Show me the bone, and I will describe the animal"

Georges Civier = French naturalist who claimed to be able to describe a whole animal from a single feature
- his Law of Correlation held that a feature of a type (such as a carniverous tooth) demanded certin features to accompany it

Cuvier's theory was not uncontroversial, at first it was rejected by the Anglican establishment, who favored the theories of Lemark as being more conudsive to religion


draws on Secord's emphasis on "knowledge in transit" rather than "science in context"

1829 - the pig's foot controversy
- cuvier had suggested that the presence of a cloven hoof indicated the presence of a ruminant with certainty, but pigs (not ruminants) sometimes leave behind cloven footprints
- "i date to call nonsense by it's true name, even when uttered by a Cuvier" - Fleming

* In Science's Shadow (Patricia Murphy, 2006)
reads a sampling of texts that show how scientific discourse is used to margninalize women

pressures to broaden women's expectations and cultural horizions, including interrogating sexual mores and the institution of marraige, led to greater gender-related anxieties
- science was a powerful weapon to stifle or stimulate social change

Darwin: "man is more powerful in body and mind than woman" and displays more invention
- children resemble the mature female more than the mature male
- contended that women had greater intuition, rapid perception—these traits were also evident of uncivilized peoples or rances
- "the chief disctiontion of the intellection powers of the two sexes is shown by man's attaining to a higher eminence in whatever he takes up than woman, whether requireing deep thought, imagination, or the uses of the senses or hands"

literature published after /Descent/ shows a casual familiarity with prevailing scientific theories
- Tennyson's /im memorium/ shows knowledge of the earth's formation, humanities' beginnings, and evolutionary progression
- /Jane Eyre/ and /Wuthering Heights/ (among others) feature the minor figure of the physician 
- /Water-Babies/ based on evolution
- psychology of madness captured popular imagination
- also analyzes the adventure novel


she focuses on non-canonical novels following the publication of /Descent of Man/ in 1871: Dickens, Brontes were dead, Tennyson was in his Arthurian period, etc.

gives chapter progressions from oblique references to science to developing theories of male superiority in science to reactionary invective against a transgressive female figure to a female voice of reason to a more optimistic resolution

1869: Anthropologist McGregor Allan wrote "On the Real Differences in the Minds of Men and Woman"
- "man's realm is the intellect, woman's the affections"

other scientific distctions
- men are "catebolic" (more active), women "anabolic" (less active)
- women were to be the complement or companion in relation to men

* Descent of Man (Darwin)
difference in the capabilities between species is a difference in degree, not of kind
- compares religion in man to fetishism in "savages", suggesting that moral/social instincts evolve

says that the bones and other stuructures of man are the same as the structures in primates, bats, etc
- brain is essentailly the same
- monkeys are liable to very similar diseases
- monkeys like coffe, rum, tobacco
- man has similar internal and external parasites to other animals
- monkeys are very helpless when born like human children
- sex differences between men and women (size, hariness) are somewhat similar to those in other primates
- man develops from similar ovules
- reproduction is very similar in all mammals

Darwin uses a preponderance of evidence to sohw that man is an animal as other animals
- telling that he has to give so much evidence for something that is essentially obvious (except that it's not)

points to "rudimentary" (vestigial) organs as evidence of evolution

Darwin still uses terms "higher" and "lower"
- ability to move the ear is rudimentary, as it helps many animals but not man

also talks about "occasional" structures, which are similar to those artiulated in /The Spandrels of San Marco/ 

* Rules of Darkness (Patrick Brantlinger, 1988)
book maps the development of the Victorian imperialist ideology
- book assumes that discourse is a form of power (Foucault), so what the Victorians said and thought about thier global project mattered
- stated aim of reducing imperialist ideology in the present

before the 1960s, scholars treated the early Victorian period with scant reference to imperialism
the word imperialism itself had its own contentions
- does it refer only to formal acts of colonial aggrandizement?
- can it refer also to ideological positions such as jingoism/patriotism and racial superiority?
- if you look at empire-building as an economic and political process, you might not consider the early-mid Victorians as imperialists because they were not jingoistic
- the "easy confidence" of early-mid Victorians was an imperialist mode

reacts against this claim: "no one in Dickens, Thackeray, Eliot, or rollope broooded about the imperial relationship"

1830s-1870s: Vics want to grant some indpeendence to colonies
- after troubles in India and Ireland, Vics more conservative about colonies

imperialist ideology
- chauvinism
- advocacy of use of military force to settle colonial disputes
- belief in "civilizing mission" (and racial) superiority

notes an evident desire in modern scholarship (as of 1980s) to downplay the imperial

"Said defines orientalism as 
a kind of Western projection onto and will to govern over the Orient' that manifests itself over the last two centuries in innumerable cultural productions, from the social sciences to the popular arts.
Race is a weakness of Marxist criticism of imperialism

during the 1860s, the word "imperial" denoted the Napoleonic project of imperialism, but the term "the colonies" was frequently used

* The Lost World (Doyle)
"The big blank spaces in the map are all being filled in, and there's no room for romance anywhere." (very Weberian)
"the peaceful penetration of Maple White Land was before us"

the chasm and the lost tree bridging it seem like represenations of the fabled missing link

Professor Challenger: to his scientific eye, the leech is as beautiful as a peacock (from Darwinian perspective)
* The Darwinian Heritage (ed. David Kohin)

** Sulloway, chapter 4: an overview of the Beagle voyage
uses "content analysis" on Darwin's letters
- uses a word-by-word analysis of documents to reveal themes and patterns
- analyzes word occurance, groupings of words...seems to be early topic modelling

traces movement from exuberance of discovery to analysis
- in beginning, category of size and of entymology cooccur

during an unconfident period, Darwin describes himself as a "Baron Munchhausen amoung scientists" to Henslow in a letter
- also "i am nothing more than a lion's provider" ... "they are likely to eat me"

Beagle voyage was 1831
/Origin/ was 1859
some have tried to read the Beagle voayge as /Origin/ writ large, but Himmelfarb (among others) tries to be more realistic, saying that his eureka moments happened after returning

* Magic, Science, and Empire in Postcolonial Literature (Kathleen J. Renk)
in intro, holds up the hermetic tradition in opposition to the totalizing view of science as empiricism and "empireism" 

/Somnium/: novel by Johannes Kepler about a boy who tavels to the moon with his witch mother

/Doctor Copernicus/: 

* Erewhon (Samuel Butler)
beginning (the back country, shepherds, exploring mountain ranges) was inspired by Butler's travels to New Zealand

the Erewhenians treat those with diseases like criminals and criminals like those with diseases

they were very technologically advanced until one of their scholars wrote a hypothetical tract about how machines would ultimately supplant humanity
- very post-human


relates machines to evolution
- lower animals are quite primitive, like present machines
- "is it not safer to nip the mischief in the bud and forbid them further progress?" - the argument is that machines the progress of machines will overtake the progress of animals, making humans superfluous
- makes a good argument about the mechanical and the willed: if the venus flytrap eat flies and not otherrandom detrius, which one might be said is only mechanical...but clearly it is mechanical in its own self interest. if such a sa simple organizorganism can be mechanicalself-interested, what is to stop a machine from being self-interested?
- "even a potato in a dark cellar has a certain low cunning that serves him in excellent stead
- "the potato says these things by doing them"
"i fear none of the existing machines.  what i fear is the extraordinary rapidity
rapidity with which they are becoming something very different from what they are at present
- "should not that movement be jealously watchedand checked while we can still check it?""


fascinatingly, here he anticipates protocols: "by the machine's own construction"

also anticipates the cyborg argument: man  is useless unless he tacks machines on to himself, without machines he cannot do things like see the spots on the moon
will man not become a "machine-tickling aphid"?

man's very soul is due to the machines.he thinks as he thinks, and feels as he feels through the work that machines have wrought upon him"
"what an army of servants do the machines thus employ" - the scuttler is a cook for the steam engine, etc, there are more men employed tending machines than tending men

argues that machines will also be able to build machines, so reproduction is no differentiator that sets animals apart
actually makes the very interesting argument that machines already have a reproductive system...we are in a symbiotic relationship with them, just as bees are required for clover to reproduce
man came about through the molding and changes of millions of years, but his advancement never came about as fast as the machines are advancing

if a plant in the early history of the world could have thought about its stante, would it not have been ridiculous for it to think that animals would one day become /real/ vegetables?
- isn't it also silly to think that there cannot be a higher form of life than ours?
- also silly to think that machines do not have a form of life
"the wonder is that there can be as much certainty about human action as there is"
- makes the point about the world being deterministic because the future is based on the present, and the present is based on the past, and the past is fixed
- makes interesting arguments about free will: image a driver on a train. it's hard to imagine the train failing to move forward deterministically based on the laws that govern it, but it seems as if the man could stop the train any time he desired. However, he can only desire to stop the train given certain relatively predictable stimuli or causes.
spontenaiety is only a term for man's ignorance of the gods

the argument proposed against the necessary descrition of machines (so that they do not supercede mankind) is a cyborg argument:
- machines are merely extensions of the organism that is man; man is machinate
- a spade is an extension of the limb, etc
- language here very rem. of cyborgs
- "if we are wet we are furnished with an organ commonly called an umbrella"
- "that old philisophic enemy, matter, still hangs about the neck of the poor man and strangles him"

satirizes a philosopher who argues for vegetarianism, arguing it as a moral progressin
* Deadly Encounters
northumberland street affair
Major Murray

1861: "sensation was the sensation"
- a craze that lasted a decade
- murders in the summer of 1861 started craze for sensation

poisonings, family of six and lover with arsenic-laced hot chocolate
Constance Kent, murderer in the case from The Suspicions of Mr. Witcher
French acrobat, worked at Crystal Palace, did feats such as cooking himself an omlet on the tightrope
warehouse fire burned a quarter mile of waterfront property

Murray: Northumberland Street Affair
- "murderous encounter in Nothumberland Street"
- also called "frightful encounter" and "deadly encounter" and "desperate affray"
- after meeting a man calling himself Gray in the street, Murray, a military man, was brought to his office here he was shot
- Gray (later identified as Roberts) thinks Murray is dead, giving Murray the oppurtunity to attack him with a set of tongs
- bloody melee ensues, leaving the office covered in blood (later sensationally described in the papers, saying the blood was like a rainstorm)
- readers were allowed to "sup full of horrors" as the newspapers described the incident and the scene in dramatic and extensive detail
- suspicion was that there was a "woman at the bottom" of the incident

- could Murray have shot himself? "it would appear to have been a mode of self-destruction available only to a despondent contortionist"
- extensive descriptions of Mrs. Murray, who had been meeting with Roberts before the incident: "an air of calculation in her dress and demeanor"
- according to Mrs. Murray, Roberts had lent her money and implied that she wouldn't have to pay it back if she did the obvious--she turned that down but couldn't pay anything but the interest

* The Beetle
champnell is a "confidental agent" love it

Robert Holt is susceptible because he is down on his luck, if he had been wearing proper clothes he would have been more resistant to mesmerism

It was as if some strong magnetic current had been switched on to me through the window to draw me into the room.

 'Pray, sir, are you a magician?'
He replied to my question with another.
'You, Mr Atherton,--are you also a magician?'

* Victorian Science in contexxt (Lightman, 1997)
this book is contextualist, which moves away from sweeping intellectual history to ask about local power relations. "Who's truth?" is the main question here. 

the book examines victorian science and comes away with an impression of victorian culture

argues that science doesn't stand apart, needs to be considered in the context of victorian culutre, both to understand victorian science and to understand victorian culture

observes a distinction between an old guard of Tory/Anglican scientists who were upper class and more religious and that controlled Oxbridge and the societies (Charles Lyell, Adam Sedgwick, William Whewell, andJohn Herschel)) and a set of middle class scientists that were more secular (Huxley, Spencer, Tyndall, William Clifford, Lewes, Edward Tylor, John Lubbock, Edwin Lankester, Edward Clodd, and Henry Maudsley)
- new group put forth more naturalistic (in the sense of immenance, or presence in the world)

telaks about the externalism/internalism debate in the history of science in the 1960s
- the Hessen theory (externalist) was that Newton's /Principia/ was created to cater to the goals if 17th century industry and economy, and that Newton was inspired by his economic status and context. Hessen's theory may itself have been influenced by internal Soviet politics, he was obliquely defending Einstein
- science, technology, and war are linked
- internalism focuses on the rational reconstuction of scientific ideas and the development of scientific ideas within the scientific world

science central to victorian culture
- ceremonial, funerals of Kelvin and Darwin
- spectacular, Crystal Palace exhibition
- sensational, /Vestiges of Creation/

victorian science colored literature
- hardy's /Jude the Obscure/ was Darwinian
- Eliot was an amateur naturalist, Lydgate in /Middlemarch/ a scientific character
- Tennyson's /Memorium/ explores religious doubts
- /Hard Times/ explores narrowness of utilitarian perspective
- Butler campaigned against Darwinian theory but also wrote books on evoution (from a Lamarkian perspective)
- Ruskin head of geological society

gentlemen of science were in a unique position to reinterpret sources of social order

** Chapter: Satire and Science in Victorian Culture by James Paradis
** Part I: Defining knowledge
intro talks about Carlyle /Sartor Ressartus/, which is at once a parody of science and an unstable grasping at truth
- carlyle uses the aesthetics of science to explore a word in which science is irrelevant
- "in accouting for everything, science ends in accouting for nothing"

Victorian scientists had to demarcate true science from false science

** Orthodoxy and Unorthodoy (Alison Winters)
becoming harder to lump old-school Oxbridge gentlemen scientists together, their positions and science itself in the 19th century were underdetermined and multivalent

uses the term heterodox science instead of derogatory pseudoscience
"retrospectively regard as heterodox or marginal cannot be considered
unambiguously to have held that status at a time when no clear orthodoxy existed that could confer that status upon them." (winters 26)
- some scientists focused on immanence, some on transcendance
- could also choose beteeen a monistic view of the world (spirit and matter unified)

** Part II: Ordering Nature
Society has scientists read into nature a variety of messages charged with ideological significance
** Part III: Practising Science
How did mechanisms and conventions of science influence the dieas of victoain scientists?

literature became a way for victorian scientists to disseminate their ideas (water babies, etc), often quite reductively. Satire could resist scientific reductionism here

* darwin's plots (Gillian Beer)
the human, everywhere and nowhere in his argument
reference's Dawkin's memes

Darwin produces different narratives
- sociobiology, genetic determinism
- proliferation of genes can produce diverse outcomes
- cloning is the contrary of evolution

Darwin's plots are
- garden, growing
- plans, mechanations

darwin's non-technical language allowed his ideas to be adopted

the origin "included more than its maker knew, despite all he did know"

darwin wanted to know if hybridism produces sterility

see darwin as less assured and more deflected by insight than major biographies
- feels that darwin is less a stereotypical product of his time, has empathy for other forms of life and assays ideas contrary to his time

points out cuthington, darwin's servant, who is not mentioned on any page of the book

taxonomies always cause trouble with boundaries
- they draw on prior assumptions
- "their values tend to form an evidential circle about what matters for categorization"

darwin questions the categorizing zeal of human beings
- my note: interesting in light of Gould's criticisms about the overzealousness of those looking to use adaptation as an explanation for all traits (Spandrels of San Marco)

major theories tax, aff
- distrub assumed relationships
- shift what is substantial into metaphor ("earth now only seems immovable")

in 1850s and 1860s, evolution was called the "development hypothesis"

"if" theory > description > cosmology > quotidian techniques and procedures

reading the Origin involves you in a narrative experience, subjective and literary

we live in a post-freudian age, his ideas are institutionalized
- the years after darwin were a post-darwinian age, his ideas seeped into the culture to the point that it didn't matter if someone had read his book or not (almost)

in our own day scientific ideas tend to reach us through translation and extrapoloation
- we use the term "layman" unironically to talk about non-scientists

darwin's theories are fundamentally multivalent, they aren't just read one way (ascent/descent, immortality/death, etc)

herschell: characterizes darwin's theory as "the law of higgldy-piggeldy"

one of the trends in reading Darwin is to try to put man back in the center of it, recasting darwin's theories to single out man

origin of species = work of biology
desacent of man = work of anthropology

* Darwin's Dangerous Idea (Dennett)
there is no going back from the (dangerous) idea that the desgined doesn't need a designer

the algorithmic level is the level that best accounts for the ... shape of the wing of the eagle
- cats can be said to make mice

* time lord
sir sanford fleming - Scottish transplant to Canada
- developed standard time


North American trains had bogies, which reduced shocks and allowed the train to go around turns without knocking everyone over
- north american trains more democratic, cars arranged with a stove in the middle and people can walk freely
- american railroads were cheaper due to the low cost of land
- america the home of luxury in transit, britain the home of speed

contends that culture, like newtonian objects, has inertia and persists until it is deflected
- uses example of china, claiming that the chinese court had a time monopoly

the ultimate time theft is slavery
- in jazz, time is a dialectic

democratic time
- wages, contracts, and patents
- rents, interest, and schedules
- recognition of impermenance of many civil institutions

not only rails, but also weather, requires standard time
regimes based on containment, like ottomans, were put in jeopardy by the new time and the new mobility

time was based on the solar noon
- but each 1100 feet is a differnt solar second

fleming found the expression local time to be objectionable
- there is no such thing, there is only one time
- guess he wasn't thinking about relativity

thoreau had anxiety about new machine time
- "we do not ride upon the railroad, it rides upon us"
- machine men have no leisure for integrity

dombey and son has a lot to say about time and the railroad

3000 miles, a six-month journey, could be covered in five days in a comfortable railroad car


** look into
thomas huxley
descent of man
vestiges of the natural history of creation
* Dracula
"my metaphor be more dishonour to science than wolves be of danger to man."

Mina's hypnotic messages from the Count like telegraphy

"I took the papers from the safe where they had been ever since our return so long ago. We were struck with the fact, that in all the mass of material of which the record is composed, there is hardly one authentic document; nothing but a mass of typewriting, except the later note-books of Mina and Seward and myself, and Van Helsing’s memorandum. We could hardly ask any one, even did we wish to, to accept these as proofs of so wild a story. "

* victorian scientists
** The X-Club (new scientists that came up in the 1870s), promoted ideological neutrality (for their own ends, accouding to Vic Science in Context)
*** Huxley
*** Tindall

*** Wallace
Attacked ideological neutrality. Wrote /Human Selection/ and /Human Progress/. For him, social progressionism and biological progressionism went hand-in-hand. Advocated for socialism and feminism.


* other useful

Sharon Marcus and Stephen Best - surface reading, goes against "symptomatic reading" that assumes that insights area always hidden below the surface

* questions
What does objectivity mean in a scientific context? How does change in scientific theories occur?
boundaries in science? between science and politics, science and religion, science and pseudoscience, ex- pert and nonexpert, orthodox and unorthodox, the material and the tran- scendent, the material and the psychological.
* beetle
"that humorous professor of hanky-panky"


* look into
The Politics of Evolution (1989), a his- tory of science "from below," by Desmond
- contrast with "Gentlemen of Science"

Sartor Resartus (1831) by Carlyle, introduces itself as a scientific study of clothes, considered that Victorian science is almost a victim of its own success because everything has been studied, critiques science as a parody



* pseudoscience
carlyle, sartor rassartis
alison winters, true and not true science


* timeline
1850 - /in memorium/ by Tennyson
1859 - /Origin of Species/

1870 - beginning of major victorian expansion


* connections to futures of the book

secord's "knowledge in transit" appraoch to large-scale current in the history of science draws on book hisotry and think of science as a form of communication
